#include <bits/stdc++.h>
using namespace std;
struct E{int to,rev,cap;};
struct Dinic{vector<vector<E>>g;vector<int>l,it;Dinic(int n):g(n),l(n),it(n){};void add(int u,int v,int c){E a{v,(int)g[v].size(),c},b{u,(int)g[u].size(),0};g[u].push_back(a);g[v].push_back(b);}bool bfs(int s,int t){fill(l.begin(),l.end(),-1);queue<int>q;l[s]=0;q.push(s);while(!q.empty()){int u=q.front();q.pop();for(auto&e:g[u])if(e.cap&&l[e.to]<0)l[e.to]=l[u]+1,q.push(e.to);}return l[t]>=0;}int dfs(int u,int t,int f){if(u==t)return f;for(int&k=it[u];k<(int)g[u].size();++k){auto&e=g[u][k];if(e.cap&&l[e.to]==l[u]+1){int z=dfs(e.to,t,min(f,e.cap));if(z){e.cap-=z;g[e.to][e.rev].cap+=z;return z;}}}return 0;}int flow(int s,int t){int z=0;while(bfs(s,t)){fill(it.begin(),it.end(),0);while(int x=dfs(s,t,1e9))z+=x;}return z;}};
bool flow_ok(const vector<int>&s,const vector<int>&rho,const vector<int>&q){int a=s.size(),b=rho.size(),S=a+b,T=S+1;Dinic F(T+1);int need=accumulate(s.begin(),s.end(),0);for(int u=0;u<b;++u){F.add(S,u,q[u]);for(int i=0;i<a;++i)if(s[i]<=rho[u])F.add(u,b+i,1);}for(int i=0;i<a;++i)F.add(b+i,T,s[i]);return F.flow(S,T)==need;}

bool exact_ok(const vector<int>&s,const vector<int>&rho,const vector<int>&q){int n=q.size(),m=s.size(),S0=n+m,T0=S0+1,SS=T0+1,TT=SS+1;Dinic F(TT+1);vector<int>bal(TT+1);auto low=[&](int u,int v,int lo,int hi){F.add(u,v,hi-lo);bal[u]-=lo;bal[v]+=lo;};int Q=accumulate(q.begin(),q.end(),0);for(int u=0;u<n;++u)low(S0,u,q[u],q[u]);for(int u=0;u<n;++u)for(int i=0;i<m;++i)if(s[i]<=rho[u])low(u,n+i,0,1);for(int i=0;i<m;++i){int hi=0;for(int u=0;u<n;++u)if(s[i]<=rho[u])++hi;if(s[i]>hi)return false;low(n+i,T0,s[i],hi);}low(T0,S0,0,Q);int need=0;for(int v=0;v<=T0;++v)if(bal[v]>0)F.add(SS,v,bal[v]),need+=bal[v];else if(bal[v]<0)F.add(v,TT,-bal[v]);return F.flow(SS,TT)==need;}
bool thresh_ok(const vector<int>&s,const vector<int>&rho,const vector<int>&q){set<int>ds(s.begin(),s.end());for(int d:ds){int dem=0,cap=0;for(int x:s)if(x>=d)dem+=x;for(int u=0;u<(int)rho.size();++u){int k=0;for(int x:s)if(x>=d&&x<=rho[u])++k;cap+=min(q[u],k);}if(dem>cap)return false;}return true;}
void seqs(int n,int mx,int lo,vector<int>&x,vector<vector<int>>&out){if((int)x.size()==n){out.push_back(x);return;}for(int v=lo;v<=mx;++v){x.push_back(v);seqs(n,mx,v,x,out);x.pop_back();}}
int main(){long long cases=0;for(int a=1;a<=4;++a)for(int b=1;b<=4;++b){vector<vector<int>>SS,RR;vector<int>x;seqs(a,b,0,x,SS);x.clear();seqs(b,b,0,x,RR);for(auto&s:SS)for(auto&rho:RR){vector<int>mx(b);for(int u=0;u<b;++u)mx[u]=count_if(s.begin(),s.end(),[&](int d){return d<=rho[u];});vector<int>q(b);function<void(int)>rec=[&](int u){if(u==b){++cases;bool f=flow_ok(s,rho,q),e=exact_ok(s,rho,q),t=thresh_ok(s,rho,q);if(f!=t||e!=t){cerr<<"MISMATCH a="<<a<<" b="<<b<<" s=";for(int z:s)cerr<<z<<",";cerr<<" rho=";for(int z:rho)cerr<<z<<",";cerr<<" q=";for(int z:q)cerr<<z<<",";cerr<<" cover="<<f<<" exact="<<e<<" thresh="<<t<<"\n";exit(1);}return;}for(q[u]=0;q[u]<=mx[u];++q[u])rec(u+1);};rec(0);}}
cout<<"cases="<<cases<<" mismatches=0 max_a=4 max_b=4\n";
}
