#!/usr/bin/env python3
"""Extend the staircase envelope dual to all source threshold layers h=1..a.

The n30 compact potential retained only tau_2,tau_3 because its semantic dual
used only those rows. This cross-order diagnostic restores a nonnegative tau_h
for every source threshold-transport inequality while keeping exactly the same
BC/SH staircase-potential logic.

Tests two dictionaries on all 38 boundary-specialised n29 t=2 survivors:
  base: specialised n30 6 BC + 3 SH shapes;
  full: base plus every distinct BC/SH shape generated by the exact n29 pairwise
        correction miner.
Floating LP feasibility is reconnaissance only.
"""
from pathlib import Path
from importlib.util import spec_from_file_location,module_from_spec
from collections import Counter
import argparse,json
import numpy as np
from scipy.optimize import linprog
from scipy.sparse import lil_matrix
HERE=Path(__file__).resolve().parent
sp=spec_from_file_location('gp',HERE/'shared_greedy_prune.py');gp=module_from_spec(sp);sp.loader.exec_module(gp)

def leq(a,b):return all(x<=y for x,y in zip(a,b))
def min_gens(g):
    pts=sorted(set(tuple(p) for p in g));return tuple(p for p in pts if not any(q!=p and leq(q,p) for q in pts))
def trim(g,dmax):return min_gens(p for p in g if p[0]<=dmax)
def tterm(rho,q,p,j):return (q if q>=j+1 else 0)-(p if rho+q>=j else 0)

class LP:
    def __init__(self):self.names=[];self.idx={};self.rows=[];self.rhs=[];self.c=[];self.bounds=[]
    def var(self,name,b=(None,None),cost=0.0):
        if name in self.idx:return self.idx[name]
        i=len(self.names);self.idx[name]=i;self.names.append(name);self.c.append(cost);self.bounds.append(b);return i
    def le(self,row,rhs):self.rows.append(row);self.rhs.append(rhs)
    def solve(self):
        A=lil_matrix((len(self.rows),len(self.names)))
        for i,r in enumerate(self.rows):
            for j,v in r.items():A[i,j]=v
        return linprog(np.array(self.c),A_ub=A.tocsr(),b_ub=np.array(self.rhs),bounds=self.bounds,method='highs')

def build(P,bcshapes,shshapes,a,b,dmax):
    M=LP();lam=M.var(('coef','lambda'),(0,None),1);cc=M.var(('coef','c'),(0,None),1);mp=M.var(('coef','mu+'),(0,None),1);mm=M.var(('coef','mu-'),(0,None),1);taus={j:M.var(('coef','tau',j),(0,None),1) for j in range(1,a+1)}
    bw=[M.var(('BC',i),(0,None),1) for i in range(len(bcshapes))];sw=[M.var(('SH',i),(0,None),1) for i in range(len(shshapes))]
    def inside(pt,g):return any(leq(q,pt) for q in g)
    def addpot(row,cb,cs,factor,sign):
        for i,g in enumerate(bcshapes):
            if inside(cb,g):row[bw[i]]=row.get(bw[i],0)+sign*factor
        for i,g in enumerate(shshapes):
            if inside(cs,g):row[sw[i]]=row.get(sw[i],0)+sign*factor
    for pi,pf in enumerate(P):
        sc=Counter(pf['s']);rc=Counter(pf['rho']);ells={};sigs={}
        for s,n in sorted(sc.items()):
            e=M.var(('ell',pi,s),(None,None));ells[s]=e
            for R in range(dmax-s+1):
                for x in range(s,b-R+1):
                    row={e:1,lam:-R,cc:-x};addpot(row,(R+s,-(R+x)),(s,-(R+x)),x,-1);M.le(row,0)
        for rho,n in sorted(rc.items()):
            sg=M.var(('sig',pi,rho),(None,None));sigs[rho]=sg;qmax=min(a-rho,sum(si<=rho for si in pf['s']))
            for q in range(qmax+1):
                pmax=min(rho+b-a-1,b-1-q)
                for pp in range(pmax+1):
                    row={sg:1,mp:-(q-pp),mm:(q-pp),cc:q}
                    for j,tv in ((j,tterm(rho,q,pp,j)) for j in range(1,a+1)):
                        if tv:row[taus[j]]=row.get(taus[j],0)-tv
                    addpot(row,(rho+q-1,-(q+pp)),(rho,-(q+pp)),q,1);M.le(row,0)
        r=sum(pf['rho']);row={lam:r}
        for s,n in sc.items():row[ells[s]]=row.get(ells[s],0)-n
        for rho,n in rc.items():row[sigs[rho]]=row.get(sigs[rho],0)-n
        M.le(row,-1)
    return M

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--boundary-json',type=Path,required=True);ap.add_argument('--support-json',type=Path,required=True);ap.add_argument('--correction-json',type=Path,required=True);ap.add_argument('--a',type=int,required=True);ap.add_argument('--b',type=int,required=True);ap.add_argument('--dmax',type=int,required=True);ap.add_argument('--output',type=Path,required=True);z=ap.parse_args()
    B=json.loads(z.boundary_json.read_text());S=json.loads(z.support_json.read_text());C=json.loads(z.correction_json.read_text());P=[{'s':r['s'],'rho':r['rho'],'demand_id':r['demand_id']} for r in B['trimmed_survivor_records']]
    basebc={trim(tuple(tuple(p) for p in x['generators']),z.dmax) for x in S['active_BC']};basesh={tuple(tuple(p) for p in x['generators']) for x in S['active_SH']};fullbc=set(basebc);fullsh=set(basesh)
    for r in C['records']:
        for x in r['cuts']:
            g=tuple(tuple(p) for p in x['generators']);(fullbc if x['family']=='BC' else fullsh).add(g)
    modes={'base':(sorted(basebc),sorted(basesh)),'full':(sorted(fullbc),sorted(fullsh))};outm={}
    for name,(bc,sh) in modes.items():
        M=build(P,bc,sh,z.a,z.b,z.dmax);res=M.solve();rec={'success':bool(res.success),'BC_shapes':len(bc),'SH_shapes':len(sh),'objective':float(res.fun) if res.success else None}
        if res.success:
            rec['active_thresholds']=[j for j in range(1,z.a+1) if res.x[M.idx[('coef','tau',j)]]>1e-8]
            rec['threshold_weights']={str(j):float(res.x[M.idx[('coef','tau',j)]]) for j in rec['active_thresholds']}
            rec['active_BC']=int(sum(res.x[M.idx[('BC',i)]]>1e-8 for i in range(len(bc))))
            rec['active_SH']=int(sum(res.x[M.idx[('SH',i)]]>1e-8 for i in range(len(sh))))
            rec['coefficients']={'lambda':float(res.x[M.idx[('coef','lambda')]]),'c':float(res.x[M.idx[('coef','c')]]),'mu':float(res.x[M.idx[('coef','mu+')]]-res.x[M.idx[('coef','mu-')]])}
        outm[name]=rec
    # Also isolate position 0 to diagnose the previously impossible singleton.
    p0=[P[0]]
    for key,(bc,sh) in modes.items():
        M=build(p0,bc,sh,z.a,z.b,z.dmax);res=M.solve();outm[key+'_position0']={'success':bool(res.success),'objective':float(res.fun) if res.success else None,'active_thresholds':[j for j in range(1,z.a+1) if res.success and res.x[M.idx[('coef','tau',j)]]>1e-8]}
    out={'schema':'n29-extended-threshold-envelope-v1','profiles':len(P),'floating_point_reconnaissance_only':True,'modes':outm,'interpretation':'Restores tau_h for all source threshold-transport layers. Tests whether n29 cross-order failure was caused by the n30-specific tau2/tau3 restriction rather than by pairwise staircase geometry.'}
    z.output.parent.mkdir(parents=True,exist_ok=True);z.output.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__':main()
