#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]

def once(s,old,new,label):
    if s.count(old)!=1:
        raise SystemExit(f'{label}: expected one anchor, found {s.count(old)}')
    return s.replace(old,new,1)

# Root README
p=ROOT/'README.md'; s=p.read_text()
anchor='A corrected `v2` model was then replayed cleanly and again produced zero survivors. The audit subsequently reduced the proof-critical `Delta=16` computation to a smaller trusted kernel, whose clean replay also produced zero survivors with every late exclusion rechecked by exact integer Farkas arithmetic. See the [public-release audit](project/reviews/n29/2026-09-08-redteam-restart-v1/PUBLIC_RELEASE_AUDIT.md) and [minimal-kernel report](project/reviews/n29/2026-09-08-redteam-restart-v1/MINIMAL_KERNEL_REPORT.json).\n'
insert=anchor+'''\n### Robustness milestone — Fan dependency removed from the current project fixed-order proofs\n\nA later external-AI critique raised three concrete objections: two possible collision/double-counting issues in the selected/residual construction, and the fact that the fixed-order papers used G. Fan's 1987 upper-density theorem to cap the edge search. The two local semantic objections did **not** survive re-audit: selection is one representative per missing **unordered** `B`-pair, and the forced cross-edges in the residual injection cannot themselves be selected because their endpoints miss an `A`-vertex. The current editions now state those points explicitly. See the [cross-cutting feedback audit](project/reviews/cross-cutting/2026-09-09-external-ai-feedback-audit-v1/REPORT.md).\n\nFor the Fan point, the project deliberately went further than defending the citation. It constructed direct order-specific upper-range reductions for **all five current project fixed-order candidates `n=25,27,28,29,30`**, so Fan's theorem is now **historical attribution only**, not a logical dependency of those proofs. Every historical reviewer-v1/proof source is retained unchanged; the current reviewer-facing surfaces are new **Fan-free v2** editions. The unified replacement is documented in [`FAN_FREE_REDUCTION.md`](project/research/fan-free-fixed-orders/2026-09-09-v1/FAN_FREE_REDUCTION.md).\n\nThe assembled replacement then passed a fresh [hostile coverage/integrity audit](project/research/fan-free-fixed-orders/2026-09-09-v1/FAN_FREE_AUDIT.md): the required upper edge ranges are complete, every proof-event checkpoint has zero survivors under exact acceptance, the v2 proof surfaces contain no residual logical invocation of Fan, and the frozen historical source hashes still match their recorded v2 provenance. This is **internal** robustness evidence, not external acceptance; the graph-to-residual lemmas and short hand monotonicity arguments remain important review targets.\n'''
s=once(s,anchor,insert,'README robustness insertion')
repls={
'**Candidate:** `e(G) <= 156`, equality only `K(12,13)`. [Reviewer release](releases/n25-reviewer-v1/README.md) · [frozen proof](project/reviews/n25/2026-09-06-full-chain-candidate-v1/PROOF.md) · [8 September re-audit](project/reviews/n25/2026-09-08-reaudit-v1/README.md).':
'**Candidate:** `e(G) <= 156`, equality only `K(12,13)`. [**Fan-free reviewer v2**](releases/n25-reviewer-v2/README.md) · [current Fan-free proof](project/reviews/n25/2026-09-09-fan-free-v2/PROOF.md) · [historical reviewer v1](releases/n25-reviewer-v1/README.md) · [8 September re-audit](project/reviews/n25/2026-09-08-reaudit-v1/README.md).',
'**Candidate:** `e(G) <= 182`, equality only `K(13,14)`. [Reviewer release](releases/n27-reviewer-v1/README.md) · [proof](project/reviews/n27/2026-09-07-candidate-v1/PROOF.md) · [evidence release](releases/n27-candidate-v1/README.md) · [8 September red-team audit](project/reviews/n27/2026-09-08-redteam-v1/REPORT.md).':
'**Candidate:** `e(G) <= 182`, equality only `K(13,14)`. [**Fan-free reviewer v2**](releases/n27-reviewer-v2/README.md) · [current Fan-free proof](project/reviews/n27/2026-09-09-fan-free-v2/PROOF.md) · [historical reviewer v1](releases/n27-reviewer-v1/README.md) · [evidence release](releases/n27-candidate-v1/README.md) · [8 September red-team audit](project/reviews/n27/2026-09-08-redteam-v1/REPORT.md).',
'**Candidate:** `e(G) <= 196`, equality only `K(14,14)`. [Reviewer release](releases/n28-reviewer-v1/README.md) · [direct 197-edge exclusion](project/research/general_n/2026-09-07-direct-197-v8/README.md) · [red-team report](project/reviews/n28/2026-09-07-redteam-v1/REPORT.md).':
'**Candidate:** `e(G) <= 196`, equality only `K(14,14)`. [**Fan-free reviewer v2**](releases/n28-reviewer-v2/README.md) · [current Fan-free proof](project/reviews/n28/2026-09-09-fan-free-v2/PROOF.tex) · [historical reviewer v1](releases/n28-reviewer-v1/README.md) · [direct 197-edge exclusion](project/research/general_n/2026-09-07-direct-197-v8/README.md) · [red-team report](project/reviews/n28/2026-09-07-redteam-v1/REPORT.md).',
'[Reviewer release](releases/n29-reviewer-v1/README.md) · [full proof and replay guide](project/reviews/n29/2026-09-08-candidate-v1/README.md) · [candidate manuscript](project/reviews/n29/2026-09-08-candidate-v1/PROOF.md)':
'[**Fan-free reviewer v2**](releases/n29-reviewer-v2/README.md) · [current Fan-free proof](project/reviews/n29/2026-09-09-fan-free-v2/PROOF.md) · [historical reviewer v1](releases/n29-reviewer-v1/README.md) · [historical proof/replay guide](project/reviews/n29/2026-09-08-candidate-v1/README.md)',
"The proof does **not** depend on the later general profile-integral candidates. Fan's cited strict bound leaves only 211 edges to exclude.":
'The proof does **not** depend on the later general profile-integral candidates or on Fan\'s density theorem. The direct Fan-free upper-range reduction excludes every `m>=212`, leaving 211 edges as the sole upper-bound counterexample scope.',
'[Reviewer release](releases/n30-reviewer-v1/README.md) · [candidate package](project/reviews/n30/2026-09-09-candidate-v1/README.md) · [assembled proof](project/reviews/n30/2026-09-09-candidate-v1/PROOF.md)':
'[**Fan-free reviewer v2**](releases/n30-reviewer-v2/README.md) · [current Fan-free proof](project/reviews/n30/2026-09-09-fan-free-v2/PROOF.md) · [historical reviewer v1](releases/n30-reviewer-v1/README.md) · [historical candidate package](project/reviews/n30/2026-09-09-candidate-v1/README.md)',
"Fan's cited strict bound leaves only 226 edges as a possible upper-bound counterexample.":
'Fan\'s density theorem is no longer used logically. The direct Fan-free upper-range reduction excludes every `m>=227`, leaving 226 edges as the sole upper-bound counterexample scope.'
}
for old,new in repls.items(): s=once(s,old,new,'README replacement')
p.write_text(s)

# Reviewer landing page
p=ROOT/'START_HERE_FOR_REVIEWERS.md'; s=p.read_text()
anchor='Paul Lenz directed the project and chose the research priorities. ChatGPT/Geeps supplied the mathematical development, implementations, manuscripts and internal audits.\n'
insert=anchor+'''\n## Robustness milestone: Fan-free fixed-order v2 editions\n\nA hostile external-AI critique questioned both selected/residual semantics and the use of G. Fan's 1987 density theorem as an edge-count cap. The semantic objections were re-audited and resolved explicitly in the current proof text. The project then removed Fan as a **logical dependency** from its current fixed-order candidate proofs at `n=25,27,28,29,30`, while retaining Fan's theorem as historical attribution and preserving every reviewer-v1/proof source unchanged.\n\nReviewers should therefore use the **Fan-free reviewer-v2 packages** listed in [`releases/REVIEW_READY_INDEX.md`](releases/REVIEW_READY_INDEX.md). The direct replacement is [`FAN_FREE_REDUCTION.md`](project/research/fan-free-fixed-orders/2026-09-09-v1/FAN_FREE_REDUCTION.md), and its assembled edge-range/source-integrity checks are recorded in [`FAN_FREE_AUDIT.md`](project/research/fan-free-fixed-orders/2026-09-09-v1/FAN_FREE_AUDIT.md). The audit is internal; independent review of the graph-theoretic bridge remains open.\n'''
s=once(s,anchor,insert,'START robustness insertion')
s=s.replace('- [`project/reviews/n29/2026-09-08-candidate-v1/PROOF.md`](project/reviews/n29/2026-09-08-candidate-v1/PROOF.md)',
            '- [`project/reviews/n29/2026-09-09-fan-free-v2/PROOF.md`](project/reviews/n29/2026-09-09-fan-free-v2/PROOF.md) — current Fan-free edition; [historical v1](project/reviews/n29/2026-09-08-candidate-v1/PROOF.md)')
s=s.replace('- [`project/reviews/n30/2026-09-09-candidate-v1/PROOF.md`](project/reviews/n30/2026-09-09-candidate-v1/PROOF.md)',
            '- [`project/reviews/n30/2026-09-09-fan-free-v2/PROOF.md`](project/reviews/n30/2026-09-09-fan-free-v2/PROOF.md) — current Fan-free edition; [historical v1](project/reviews/n30/2026-09-09-candidate-v1/PROOF.md)')
s=s.replace("Fan's cited strict bound leaves only 226 edges as an upper-bound counterexample. The dense non-bipartite proof reduces to `Delta=16` and `Delta=17`; the remaining degree ranges are hand/charging exclusions.",
            "The current edition does not use Fan's density theorem logically: the direct Fan-free upper-range reduction excludes every edge count above 226. The dense non-bipartite proof then reduces the 226-edge scope to `Delta=16` and `Delta=17`; the remaining degree ranges are hand/charging exclusions.")
p.write_text(s)
print('FAN_FREE_PUBLIC_SURFACES_UPDATED')
