#include <bits/stdc++.h>
using namespace std;
struct State{int layer,id,a,b,t;vector<int>s,rho;};
struct OD{vector<vector<unsigned char>>D;vector<int>pairdeg,P;bool pass=false;};
struct CEdge{int to,rev,cap,cost;};
struct MinCostFlow{vector<vector<CEdge>>g;explicit MinCostFlow(int n):g(n){};void add(int u,int v,int cap,int cost){CEdge a{v,(int)g[v].size(),cap,cost},b{u,(int)g[u].size(),0,-cost};g[u].push_back(a);g[v].push_back(b);}pair<int,long long> flow(int s,int t,int need){const long long INF=(1LL<<60);int sent=0;long long total=0;int n=g.size();while(sent<need){vector<long long>d(n,INF);vector<int>pv(n,-1),pe(n,-1);vector<char>inq(n);queue<int>q;d[s]=0;q.push(s);inq[s]=1;while(!q.empty()){int u=q.front();q.pop();inq[u]=0;for(int k=0;k<(int)g[u].size();++k){auto const&e=g[u][k];if(!e.cap||d[u]==INF)continue;long long nd=d[u]+e.cost;if(nd<d[e.to]){d[e.to]=nd;pv[e.to]=u;pe[e.to]=k;if(!inq[e.to])inq[e.to]=1,q.push(e.to);}}}if(d[t]==INF)break;int add=need-sent;for(int v=t;v!=s;v=pv[v])add=min(add,g[pv[v]][pe[v]].cap);for(int v=t;v!=s;v=pv[v]){auto&e=g[pv[v]][pe[v]];e.cap-=add;g[v][e.rev].cap+=add;}sent+=add;total+=1LL*add*d[t];}return{sent,total};}};
static map<tuple<int,int,int>,vector<vector<int>>> pcache;
static void gp(int pos,int cnt,int last,int mx,int rem,vector<int>&cur,vector<vector<int>>&out){if(pos==cnt){if(rem==0)out.push_back(cur);return;}int left=cnt-pos-1;for(int x=last;x<=mx&&x<=rem;++x){int rr=rem-x;if(rr<x*left||rr>mx*left)continue;cur[pos]=x;gp(pos+1,cnt,x,mx,rr,cur,out);}}
static const vector<vector<int>>& parts(int cnt,int mx,int sum){auto k=make_tuple(cnt,mx,sum);auto it=pcache.find(k);if(it!=pcache.end())return it->second;vector<vector<int>>o;if(cnt==0){if(sum==0)o.push_back({});}else if(sum>=0&&sum<=cnt*mx){vector<int>c(cnt);gp(0,cnt,0,mx,sum,c,o);}return pcache.emplace(k,move(o)).first->second;}
static pair<bool,int> core_partition(const vector<int>&caps,const vector<int>&loss,int h,int m){if(h<=0||m<=0)return {true,0};long long tot=0;for(int c:caps)tot+=min(c,m);if(tot<1LL*h*m)return {false,INT_MAX};map<vector<int>,int>dp;dp[vector<int>(h,0)]=0;for(size_t z=0;z<caps.size();++z){int cap=min(caps[z],m),w=loss.empty()?0:loss[z];map<vector<int>,int>nd=dp;for(auto const&kv:dp){int last=-1;for(int j=0;j<h;++j){if(kv.first[j]==last)continue;last=kv.first[j];auto ns=kv.first;ns[j]=min(m,ns[j]+cap);sort(ns.begin(),ns.end());int nc=kv.second+w;auto it=nd.find(ns);if(it==nd.end()||nc<it->second)nd[move(ns)]=nc;}}dp.swap(nd);}vector<int>tar(h,m);auto it=dp.find(tar);return it==dp.end()?make_pair(false,INT_MAX):make_pair(true,it->second);}
static bool corefail(const State&st,const vector<int>&q){set<int>rs(st.rho.begin(),st.rho.end());for(int r:rs){int h=count_if(st.s.begin(),st.s.end(),[&](int d){return d<=r;});if(!h)continue;vector<int>U;for(int u=0;u<(int)q.size();++u)if(st.rho[u]==r&&q[u]==h)U.push_back(u);if(U.empty())continue;int m=U.size();vector<char>isU(q.size());for(int u:U)isU[u]=1;vector<int>cand,caps;for(int v=0;v<(int)q.size();++v){int c=st.rho[v]+st.b-st.a-1;if(!isU[v]&&q[v]<=h+r-1&&q[v]+st.rho[v]>=h-1&&c>0){cand.push_back(v);caps.push_back(c);}}vector<int>zero(caps.size());auto [ok,z]=core_partition(caps,zero,h,m);if(!ok)return true;set<int>taus;for(int d:st.s)if(d>r)taus.insert(d);for(int tau:taus){int raw=0;for(int v=0;v<(int)q.size();++v)if(st.rho[v]>=tau)raw+=q[v];int demand=0;for(int d:st.s)if(d>=tau)demand+=d;vector<int>loss;for(int v:cand)loss.push_back(st.rho[v]>=tau?max(0,q[v]-r):0);auto [ok2,minloss]=core_partition(caps,loss,h,m);if(!ok2){cerr<<"internal core error\n";exit(3);}if(raw-minloss<demand)return true;}}return false;}
static OD paircap(const State&st,const vector<int>&q,int E){int n=q.size(),Q=accumulate(q.begin(),q.end(),0),z=count(st.s.begin(),st.s.end(),0);OD o;o.D.assign(n,vector<unsigned char>(n));vector<int>c(n);for(int i=0;i<n;++i)c[i]=q[i]+st.rho[i];for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(i!=j&&q[i]<=c[j]+1&&q[j]<=c[i])o.D[i][j]=1;o.pairdeg.assign(n,0);for(int i=0;i<n;++i)for(int j=i+1;j<n;++j)if(o.D[i][j]||o.D[j][i])o.pairdeg[i]++,o.pairdeg[j]++;o.P.resize(n);long long sumP=0;bool nonneg=true;for(int i=0;i<n;++i){int p=min(st.rho[i]+st.b-st.a-1,st.b-1-q[i]);if(q[i]>0){int kstar=min(z,min(q[i],E));if(q[i]>kstar){int extra=(E-kstar)/(q[i]-kstar);p=min(p,st.rho[i]+extra-1);}}p=min(p,o.pairdeg[i]-q[i]);o.P[i]=p;if(p<0)nonneg=false;else sumP+=p;}o.pass=nonneg&&sumP>=Q;return o;}
static bool incidence_threshold_fail(const State&st,const vector<int>&q){set<int>ds(st.s.begin(),st.s.end());for(int d:ds){vector<int>L;for(int i=0;i<(int)st.s.size();++i)if(st.s[i]>=d)L.push_back(i);if(L.empty())continue;int dem=0;for(int i:L)dem+=st.s[i];int cap=0;for(int u=0;u<(int)q.size();++u){int elig=0;for(int i:L)if(st.s[i]<=st.rho[u])elig++;cap+=min(q[u],elig);}if(dem>cap)return true;}return false;}
static bool pair_threshold_fail(const State&st,const vector<int>&q,const OD&o){int n=q.size();set<int>Rs(st.rho.begin(),st.rho.end());int qmx=*max_element(q.begin(),q.end());for(int R:Rs)for(int k=1;k<=qmx;++k){vector<int>X;vector<char>in(n);for(int i=0;i<n;++i)if(st.rho[i]>=R&&q[i]>=k)X.push_back(i),in[i]=1;if(X.empty())continue;int dem=0;for(int i:X)dem+=q[i];int cap=0;for(int i=0;i<n;++i)for(int j=i+1;j<n;++j){bool adj=(in[i]&&o.D[i][j])||(in[j]&&o.D[j][i]);if(adj)cap++;}if(dem>cap)return true;}return false;}
static bool target_threshold_fail(const State&st,const vector<int>&q,const OD&o){int n=q.size();set<int>Rs(st.rho.begin(),st.rho.end());int qmx=*max_element(q.begin(),q.end());for(int R:Rs)for(int k=1;k<=qmx;++k){vector<int>X;vector<char>in(n);for(int i=0;i<n;++i)if(st.rho[i]>=R&&q[i]>=k)X.push_back(i),in[i]=1;if(X.empty())continue;int dem=0;for(int i:X)dem+=q[i];int cap=0;for(int j=0;j<n;++j){int dx=0;for(int i:X)if(o.D[i][j])dx++;cap+=min(max(0,o.P[j]),dx);}if(dem>cap)return true;}return false;}
static long long excess_envelope(const State&st,int E){if(any_of(st.s.begin(),st.s.end(),[](int x){return x<=0;}))return -1;const long long NEG=-(1LL<<50);vector<long long>dp(E+1,NEG);dp[0]=0;for(int d:st.s){int h=count_if(st.rho.begin(),st.rho.end(),[&](int r){return r>=d;});if(h<d)return NEG;int cap=h-d;vector<long long>ndp(E+1,NEG);for(int used=0;used<=E;++used)if(dp[used]>NEG/2)for(int e=0;e<=cap&&used+e<=E;++e)ndp[used+e]=max(ndp[used+e],dp[used]+1LL*(d+e)*e);dp.swap(ndp);}return dp[E];}
static pair<int,long long> target_cost_flow(const State&st,const vector<int>&q,const OD&o){int n=q.size(),Q=accumulate(q.begin(),q.end(),0),S=2*n,T=S+1;MinCostFlow F(T+1);for(int i=0;i<n;++i)F.add(S,i,q[i],0);for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(o.D[i][j])F.add(i,n+j,1,0);for(int j=0;j<n;++j){int freecap=min(max(0,o.P[j]),max(0,st.rho[j]-1));if(freecap)F.add(n+j,T,freecap,0);int paid=max(0,o.P[j]-freecap);if(paid)F.add(n+j,T,paid,q[j]);}return F.flow(S,T,Q);}
static State load(const string&fn,int want){ifstream f(fn);int N;f>>N;for(int z=0;z<N;++z){State st;int ns,nr;f>>st.layer>>st.id>>st.a>>st.b>>st.t>>ns;st.s.resize(ns);for(int&x:st.s)f>>x;f>>nr;st.rho.resize(nr);for(int&x:st.rho)f>>x;if(st.id==want)return st;}throw runtime_error("not found");}
int main(int ac,char**av){if(ac<3)return 2;State st=load(av[1],stoi(av[2]));int S=accumulate(st.s.begin(),st.s.end(),0);map<int,int>ct;for(int r:st.rho)ct[r]++;struct C{int r,c,mx;};vector<C>cs;int maxQ=0;for(auto [r,c]:ct){int h=count_if(st.s.begin(),st.s.end(),[&](int d){return d<=r;});int mx=max(0,min(st.a-r,h));cs.push_back({r,c,mx});maxQ+=c*mx;}int U=accumulate(st.rho.begin(),st.rho.end(),0)+st.b*(st.b-st.a-1);int Qmax=min({maxQ,U,st.b*(st.b-1)/2});long long prof=0,core=0,pc=0,inc=0,pair=0,target=0,left=0,fallback_hall=0,costfail=0,finalleft=0; vector<tuple<int,vector<int>,long long,long long>> costcerts;for(int Q=S;Q<=Qmax;++Q){int E=Q-S;function<void(int,int,vector<int>&)>rec=[&](int ci,int rem,vector<int>&q){if(ci==(int)cs.size()){if(rem)return;prof++;if(corefail(st,q)){core++;return;}auto o=paircap(st,q,E);if(!o.pass){pc++;return;}if(incidence_threshold_fail(st,q)){inc++;return;}if(pair_threshold_fail(st,q,o)){pair++;return;}if(target_threshold_fail(st,q,o)){target++;return;}left++;{auto [ff,cc]=target_cost_flow(st,q,o);long long env=excess_envelope(st,E);if(ff<Q){fallback_hall++;return;}if(env>=0&&cc>env){costfail++;costcerts.push_back({E,q,cc,env});return;}finalleft++;return;}}auto C=cs[ci];int mxrest=0;for(int j=ci+1;j<(int)cs.size();++j)mxrest+=cs[j].c*cs[j].mx;int lo=max(0,rem-mxrest),hi=min(C.c*C.mx,rem);for(int sm=lo;sm<=hi;++sm)for(auto const&p:parts(C.c,C.mx,sm)){auto old=q.size();q.insert(q.end(),p.begin(),p.end());rec(ci+1,rem-sm,q);q.resize(old);}};vector<int>q;rec(0,Q,q);}cout<<st.id<<"\t"<<prof<<"\t"<<core<<"\t"<<pc<<"\t"<<inc<<"\t"<<pair<<"\t"<<target<<"\t"<<left<<"\t"<<fallback_hall<<"\t"<<costfail<<"\t"<<finalleft<<"\n";for(auto &z:costcerts){auto [E,q,cost,env]=z;cerr<<"COSTCERT state="<<st.id<<" E="<<E<<" cost="<<cost<<" env="<<env<<" q=";for(int i=0;i<(int)q.size();++i)cerr<<(i?",":"")<<q[i];cerr<<"\n";}}
