#!/usr/bin/env python3
"""Independent direct score checks and complete conservative residual expansion.

The CSV is generated by enumerate_frontier.cpp. This implementation uses
explicit tail lists, not the C++ incremental score recurrence.
"""
import csv
import json
from collections import Counter
from pathlib import Path

HERE=Path(__file__).resolve().parent
A,B=15,18


def gamma(h,w):
    if not w:
        return 0
    z=h
    while z*(z-1)+h*(h+1)<2*w:
        z+=1
    return z


def expand(t):
    states=[]
    stats=Counter()
    for row in csv.DictReader((HERE/'FRONTIER.csv').open()):
        s=tuple(int(row['s'+str(i)]) for i in range(A))
        raw={h:gamma(h,sum(x for x in s if x>=h)) for h in range(2,A)}
        score=sum(s)-sum(raw.values())
        assert score==int(row['Q'])
        z={A:0,1:B}
        for h in range(A-1,1,-1):
            z[h]=max(raw[h],z[h+1])
        monotone=sum(s)-sum(z[h] for h in range(2,A))
        assert monotone==int(row['Q_monotone'])
        if monotone<B+2*t:
            continue
        stats['profiles']+=1
        rho0=tuple(h for h in range(1,A) for _ in range(z[h]-z[h+1]))
        assert len(rho0)==B
        slack=sum(s)-2*t-sum(rho0)
        cur={rho0}
        variants=set(cur)
        for _ in range(slack):
            nxt=set()
            for rho in cur:
                for i,r in enumerate(rho):
                    if r<A:
                        rs=list(rho);rs[i]+=1
                        nxt.add(tuple(sorted(rs)))
            variants.update(nxt);cur=nxt
        for rho in sorted(variants):
            assert sum(rho)<=sum(s)-2*t
            assert all(sum(r>=h for r in rho)>=raw[h] for h in raw)
            # Isolated-C bound and at least s_i residual-compatible sources.
            # Retain a conservative domain; no solver exclusion is used here.
            if sum(rho)>A*(A-1)//2-t-(A+1)//2:
                stats['isolated_C_excluded_states']+=1
                continue
            states.append((s,rho))
            stats['states']+=1
            stats['zero_demand_states' if min(s)==0 else 'positive_demand_states']+=1
    return states,dict(stats)


def main():
    results={}
    for t in (1,2,3,4):
        states,stats=expand(t)
        results[str(t)]=stats
        print('t=',t,stats,flush=True)
        if t>=3:
            (HERE/f'states_t{t}.json').write_text(json.dumps(states,indent=2)+'\n')
    assert [results[str(t)]['profiles'] for t in (1,2,3,4)]==[1296,337,56,2]
    (HERE/'frontier_summary.json').write_text(json.dumps(results,indent=2)+'\n')


if __name__=='__main__':
    main()
