/* GENERATED q-crossing statistics scanner; canonical decisions unchanged. */
/* GENERATED layered-receiver reach scanner; canonical decisions unchanged. */
/* GENERATED by make_compatible_copy_band_reach_scanner.py after the
   antichain and coarse-band generators. Canonical relational decisions are
   unchanged. Extra instrumentation compares coarse and compatible-copy band
   flows on each exact target-Hall-failing canonical witness. */
/* GENERATED by make_band_reach_scanner.py after make_antichain_stats_scanner.py.
   Canonical relational decisions are unchanged. Extra instrumentation measures
   whether the verified staircase-band necessary relaxation already rejects
   each exact target-Hall-failing canonical witness. */
/* GENERATED by make_antichain_stats_scanner.py.
   Mathematical decisions in the canonical scanner are unchanged.
   Extra work is audit/reconnaissance only: every labelled target-flow failure
   is cross-checked against the sharp-dominance-closed quotient max flow and
   its canonical antichain generator count is recorded. */
#include <algorithm>
#include <array>
#include <cassert>
#include <chrono>
#include <climits>
#include <cmath>
#include <fstream>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <sstream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
using namespace std;

/*
Post-pair relational frontier scanner.

Input is expected to be the ledger-current survivor frontier, so the large
potential-pair family has already been removed at state level.  Nevertheless,
for each q profile we reapply the cheap pair-capacity screen first, then spend
work only on pair-capacity survivors.

For every total excess E and every enlarged-universe q profile (up to equal-rho
permutation), the retained necessary conditions are, in cost order:

  1. canonical/simple incoming caps + TOTAL_EXCESS_SOURCE_CAP;
  2. POTENTIAL_PAIR_CAPACITY (J subseteq K_D);
  3. exact variable-x selected-incidence lower-bound circulation;
  4. unordered-pair Hall flow (one missing pair used at most once);
  5. directed target-capacity Hall flow;
  6. for all-positive-demand states, EXCESS_BUDGET_ORIENTATION_COST:
     directed compatible min-cost <= exact selection-free excess envelope M(E).

A whole state is excluded only if every q profile at every admissible E fails.
Survival is still only survival of these relaxations, not graph feasibility.
All proof-relevant arithmetic is integral; no timeout or floating infeasibility
is used as a certificate.
*/

struct Edge { int to, rev, cap; };
struct Dinic {
    vector<vector<Edge>> g;
    vector<int> level, it;
    explicit Dinic(int n): g(n), level(n), it(n) {}
    void add(int u,int v,int cap){
        Edge a{v,(int)g[v].size(),cap}, b{u,(int)g[u].size(),0};
        g[u].push_back(a); g[v].push_back(b);
    }
    bool bfs(int s,int t){
        fill(level.begin(),level.end(),-1); queue<int>q; level[s]=0;q.push(s);
        while(!q.empty()){
            int u=q.front();q.pop();
            for(auto const&e:g[u]) if(e.cap&&level[e.to]<0){level[e.to]=level[u]+1;q.push(e.to);}
        }
        return level[t]>=0;
    }
    int dfs(int u,int t,int f){
        if(u==t)return f;
        for(int &k=it[u];k<(int)g[u].size();++k){
            Edge &e=g[u][k];
            if(!e.cap||level[e.to]!=level[u]+1)continue;
            int z=dfs(e.to,t,min(f,e.cap));
            if(z){e.cap-=z;g[e.to][e.rev].cap+=z;return z;}
        }
        return 0;
    }
    int flow(int s,int t){
        int ans=0;
        while(bfs(s,t)){
            fill(it.begin(),it.end(),0);
            while(int z=dfs(s,t,INT_MAX/4))ans+=z;
        }
        return ans;
    }
};

struct CEdge { int to, rev, cap, cost; };
struct MinCostFlow {
    vector<vector<CEdge>> g;
    explicit MinCostFlow(int n): g(n) {}
    void add(int u,int v,int cap,int cost){
        CEdge a{v,(int)g[v].size(),cap,cost}, b{u,(int)g[u].size(),0,-cost};
        g[u].push_back(a);g[v].push_back(b);
    }
    pair<int,long long> flow(int s,int t,int need){
        const long long INF=(1LL<<60); int sent=0; long long total=0; int n=g.size();
        while(sent<need){
            vector<long long>d(n,INF);vector<int>pv(n,-1),pe(n,-1);vector<char>inq(n,0);
            queue<int>q;d[s]=0;q.push(s);inq[s]=1;
            while(!q.empty()){
                int u=q.front();q.pop();inq[u]=0;
                for(int k=0;k<(int)g[u].size();++k){
                    auto const&e=g[u][k];if(!e.cap||d[u]==INF)continue;
                    long long nd=d[u]+e.cost;
                    if(nd<d[e.to]){d[e.to]=nd;pv[e.to]=u;pe[e.to]=k;if(!inq[e.to]){inq[e.to]=1;q.push(e.to);}}
                }
            }
            if(d[t]==INF)break;
            int add=need-sent;
            for(int v=t;v!=s;v=pv[v])add=min(add,g[pv[v]][pe[v]].cap);
            for(int v=t;v!=s;v=pv[v]){CEdge &e=g[pv[v]][pe[v]];e.cap-=add;g[v][e.rev].cap+=add;}
            sent+=add;total+=1LL*add*d[t];
        }
        return {sent,total};
    }
};

struct State { int layer,id,a,b,t; vector<int>s,rho; };
struct Cls { int rho,cnt,qmax; };

static map<tuple<int,int,int>,vector<vector<int>>> part_cache;
static void gen_parts(int pos,int cnt,int last,int mx,int rem,vector<int>&cur,vector<vector<int>>&out){
    if(pos==cnt){if(rem==0)out.push_back(cur);return;}
    int left=cnt-pos-1;
    for(int x=last;x<=mx&&x<=rem;++x){
        int rr=rem-x;if(rr<x*left||rr>mx*left)continue;
        cur[pos]=x;gen_parts(pos+1,cnt,x,mx,rr,cur,out);
    }
}
static const vector<vector<int>>& parts(int cnt,int mx,int sum){
    auto key=make_tuple(cnt,mx,sum);auto it=part_cache.find(key);if(it!=part_cache.end())return it->second;
    vector<vector<int>>out;
    if(cnt==0){if(sum==0)out.push_back({});}
    else if(sum>=0&&sum<=cnt*mx){vector<int>cur(cnt);gen_parts(0,cnt,0,mx,sum,cur,out);}
    return part_cache.emplace(key,move(out)).first->second;
}

static void lowedge(Dinic&F,vector<int>&bal,int u,int v,int lo,int hi){
    assert(0<=lo&&lo<=hi);F.add(u,v,hi-lo);bal[u]-=lo;bal[v]+=lo;
}
static bool variable_incidence(const State&st,const vector<int>&q,const vector<int>&rho){
    int n=q.size(),m=st.s.size(),S0=n+m,T0=S0+1,SS=T0+1,TT=SS+1;
    Dinic F(TT+1);vector<int>bal(TT+1,0);int Q=accumulate(q.begin(),q.end(),0);
    for(int u=0;u<n;++u)lowedge(F,bal,S0,u,q[u],q[u]);
    for(int u=0;u<n;++u)for(int i=0;i<m;++i)if(st.s[i]<=rho[u])lowedge(F,bal,u,n+i,0,1);
    for(int i=0;i<m;++i){
        int hi=0;for(int u=0;u<n;++u)if(st.s[i]<=rho[u])++hi;
        if(st.s[i]>hi)return false;
        lowedge(F,bal,n+i,T0,st.s[i],hi);
    }
    lowedge(F,bal,T0,S0,0,Q);
    int need=0;
    for(int v=0;v<=T0;++v){
        if(bal[v]>0){F.add(SS,v,bal[v]);need+=bal[v];}
        else if(bal[v]<0)F.add(v,TT,-bal[v]);
    }
    return F.flow(SS,TT)==need;
}

static long long excess_envelope(const State&st,int E){
    if(any_of(st.s.begin(),st.s.end(),[](int x){return x<=0;}))return -1; // theorem not asserted with zero demand
    const long long NEG=-(1LL<<50);
    vector<long long>dp(E+1,NEG);dp[0]=0;
    for(int s:st.s){
        int h=count_if(st.rho.begin(),st.rho.end(),[&](int r){return r>=s;});
        if(h<s)return NEG;
        int cap=h-s;vector<long long>ndp(E+1,NEG);
        for(int used=0;used<=E;++used)if(dp[used]>NEG/2){
            for(int e=0;e<=cap&&used+e<=E;++e)
                ndp[used+e]=max(ndp[used+e],dp[used]+1LL*(s+e)*e);
        }
        dp.swap(ndp);
    }
    return dp[E];
}

struct OD { vector<vector<unsigned char>>D; vector<int>pairdeg,P,c; bool pass=false; int margin=INT_MIN; };
static OD pair_capacity(const State&st,const vector<int>&q,const vector<int>&rho,int E){
    int n=q.size(),Q=accumulate(q.begin(),q.end(),0),z=count(st.s.begin(),st.s.end(),0);
    OD o;o.c.resize(n);for(int i=0;i<n;++i)o.c[i]=q[i]+rho[i];
    o.D.assign(n,vector<unsigned char>(n,0));
    for(int i=0;i<n;++i)for(int j=0;j<n;++j)
        if(i!=j&&q[i]<=o.c[j]+1&&q[j]<=o.c[i])o.D[i][j]=1;
    o.pairdeg.assign(n,0);
    for(int i=0;i<n;++i)for(int j=i+1;j<n;++j)if(o.D[i][j]||o.D[j][i]){++o.pairdeg[i];++o.pairdeg[j];}
    o.P.resize(n);long long sumP=0;bool nonneg=true;
    for(int i=0;i<n;++i){
        int p=min(rho[i]+st.b-st.a-1,st.b-1-q[i]);
        if(q[i]>0){
            int kstar=min(z,min(q[i],E));
            if(q[i]>kstar){int extra=(E-kstar)/(q[i]-kstar);p=min(p,rho[i]+extra-1);}
        }
        p=min(p,o.pairdeg[i]-q[i]);
        o.P[i]=p;if(p<0)nonneg=false;else sumP+=p;
    }
    o.margin=nonneg?(int)(sumP-Q):INT_MIN/2;
    o.pass=nonneg&&sumP>=Q;
    return o;
}

static int pair_flow(const vector<int>&q,const OD&o){
    int n=q.size();vector<pair<int,int>>ps;
    for(int i=0;i<n;++i)for(int j=i+1;j<n;++j)if(o.D[i][j]||o.D[j][i])ps.push_back({i,j});
    int S=n+ps.size(),T=S+1;Dinic F(T+1);for(int i=0;i<n;++i)F.add(S,i,q[i]);
    for(int k=0;k<(int)ps.size();++k){auto[i,j]=ps[k];int x=n+k;if(o.D[i][j])F.add(i,x,1);if(o.D[j][i])F.add(j,x,1);F.add(x,T,1);}
    return F.flow(S,T);
}

struct HallType { int q,c,P,n; };
static bool compat_hall_type(const HallType&a,const HallType&b){
    return a.q<=b.c+1 && b.q<=a.c;
}
static bool sharp_dominates(const HallType&x,const HallType&y){
    return x.c<=y.c && (x.q>y.q || (x.q==y.q && x.P>=y.P));
}

static pair<int,int> canonical_antichain_stats(const vector<int>&q,const OD&o,int Q){
    map<tuple<int,int,int>,int> ct;
    for(int i=0;i<(int)q.size();++i)++ct[make_tuple(q[i],o.c[i],o.P[i])];
    vector<HallType> types;types.reserve(ct.size());
    for(auto const&kv:ct){auto [qq,cc,pp]=kv.first;types.push_back({qq,cc,pp,kv.second});}
    int k=types.size(),S=2*k,T=S+1;Dinic F(T+1);
    for(int i=0;i<k;++i)F.add(S,i,types[i].n*types[i].q);
    for(int i=0;i<k;++i)for(int j=0;j<k;++j)if(compat_hall_type(types[i],types[j])){
        int cap=(i==j)?types[i].n*(types[i].n-1):types[i].n*types[j].n;
        if(cap)F.add(i,k+j,cap);
    }
    for(int j=0;j<k;++j)F.add(k+j,T,types[j].n*types[j].P);
    for(int x=0;x<k;++x)for(int y=0;y<k;++y)
        if(x!=y&&sharp_dominates(types[x],types[y]))F.add(y,x,Q+1);

    int flow=F.flow(S,T);

    vector<vector<int>> rev(T+1);
    for(int u=0;u<=T;++u)for(auto const&e:F.g[u])if(e.cap>0)rev[e.to].push_back(u);
    vector<unsigned char> can(T+1,0);queue<int>qq;can[T]=1;qq.push(T);
    while(!qq.empty()){
        int v=qq.front();qq.pop();
        for(int u:rev[v])if(!can[u]){can[u]=1;qq.push(u);}
    }
    vector<unsigned char> selected(k,0);
    for(int i=0;i<k;++i)selected[i]=!can[i];

    // The residual maximal source-side cut must be a sharp hardness up-set.
    for(int y=0;y<k;++y)if(selected[y])for(int x=0;x<k;++x)
        if(x!=y&&sharp_dominates(types[x],types[y])&&!selected[x]){
            cerr<<"ANTICHAIN_UPSET_MISMATCH y="<<y<<" x="<<x<<"\n";exit(4);
        }

    int generators=0;vector<int> gens;
    for(int i=0;i<k;++i)if(selected[i]){
        bool nonminimal=false;
        for(int j=0;j<k;++j)if(j!=i&&selected[j]&&sharp_dominates(types[i],types[j])){nonminimal=true;break;}
        if(!nonminimal){++generators;gens.push_back(i);}
    }
    stable_sort(gens.begin(),gens.end(),[&](int x,int y){return types[x].c<types[y].c;});
    for(int z=1;z<(int)gens.size();++z){
        auto const&A=types[gens[z-1]];auto const&B=types[gens[z]];
        if(!(A.c<B.c&&A.q<=B.q&&(A.q!=B.q||A.P<B.P))){
            cerr<<"ANTICHAIN_STAIRCASE_MISMATCH\n";exit(5);
        }
    }
    return {flow,generators};
}

static tuple<int,int,int,int,int,int,int,int> canonical_band_flows(const vector<int>&q,const OD&o,int Q){
    map<tuple<int,int,int>,int> ct;
    for(int i=0;i<(int)q.size();++i)++ct[make_tuple(q[i],o.c[i],o.P[i])];
    vector<HallType> types;types.reserve(ct.size());
    for(auto const&kv:ct){auto [qq,cc,pp]=kv.first;types.push_back({qq,cc,pp,kv.second});}
    int k=types.size(),S=2*k,T=S+1;Dinic F(T+1);
    for(int i=0;i<k;++i)F.add(S,i,types[i].n*types[i].q);
    for(int i=0;i<k;++i)for(int j=0;j<k;++j)if(compat_hall_type(types[i],types[j])){
        int cap=(i==j)?types[i].n*(types[i].n-1):types[i].n*types[j].n;
        if(cap)F.add(i,k+j,cap);
    }
    for(int j=0;j<k;++j)F.add(k+j,T,types[j].n*types[j].P);
    for(int x=0;x<k;++x)for(int y=0;y<k;++y)
        if(x!=y&&sharp_dominates(types[x],types[y]))F.add(y,x,Q+1);
    (void)F.flow(S,T);

    vector<vector<int>> rev(T+1);
    for(int u=0;u<=T;++u)for(auto const&e:F.g[u])if(e.cap>0)rev[e.to].push_back(u);
    vector<unsigned char> can(T+1,0);queue<int>qq;can[T]=1;qq.push(T);
    while(!qq.empty()){
        int v=qq.front();qq.pop();
        for(int u:rev[v])if(!can[u]){can[u]=1;qq.push(u);}
    }
    vector<unsigned char> selected(k,0);
    for(int i=0;i<k;++i)selected[i]=!can[i];

    vector<int> gens;
    for(int i=0;i<k;++i)if(selected[i]){
        bool nonminimal=false;
        for(int j=0;j<k;++j)if(j!=i&&selected[j]&&sharp_dominates(types[i],types[j])){nonminimal=true;break;}
        if(!nonminimal)gens.push_back(i);
    }
    stable_sort(gens.begin(),gens.end(),[&](int x,int y){return types[x].c<types[y].c;});
    int h=gens.size();
    if(h==0){cerr<<"CCBAND_EMPTY_GENERATORS_ON_FAILURE\n";exit(70);}

    vector<int> band(k,-1),M(h,0),D(h,0);
    for(int t=0;t<k;++t)if(selected[t]){
        int b=-1;
        for(int i=0;i<h;++i)if(types[t].c<=types[gens[i]].c){b=i;break;}
        if(b<0){cerr<<"CCBAND_ASSIGNMENT_FAILURE\n";exit(71);}
        auto const&G=types[gens[b]];
        if(!(types[t].q>=G.q&&types[t].c<=G.c)){
            cerr<<"CCBAND_INTERVAL_CONTAINMENT_FAILURE\n";exit(72);
        }
        band[t]=b;M[b]+=types[t].n;D[b]+=types[t].n*types[t].q;
    }

    int demand=accumulate(D.begin(),D.end(),0);
    int BS=h+k,BT=BS+1;Dinic coarse(BT+1),refined(BT+1);
    for(int i=0;i<h;++i){coarse.add(BS,i,D[i]);refined.add(BS,i,D[i]);}

    for(int i=0;i<h;++i)for(int j=0;j<k;++j){
        int delta=(selected[j]&&band[j]==i)?1:0;
        int coarsecap=0;
        if(compat_hall_type(types[gens[i]],types[j])){
            int copies=M[i]-delta;
            if(copies<0){cerr<<"CCBAND_NEGATIVE_COARSE_COPIES\n";exit(73);}
            coarsecap=types[j].n*copies;
            if(coarsecap)coarse.add(i,h+j,coarsecap);
        }

        int actualcopies=0;
        for(int t=0;t<k;++t)if(selected[t]&&band[t]==i&&compat_hall_type(types[t],types[j]))
            actualcopies+=types[t].n;
        int rcopies=actualcopies-delta;
        if(rcopies<0){cerr<<"CCBAND_NEGATIVE_REFINED_COPIES\n";exit(74);}
        int refinedcap=types[j].n*rcopies;
        if(refinedcap>coarsecap){
            cerr<<"CCBAND_REFINEMENT_EXCEEDS_COARSE i="<<i<<" target="<<j
                <<" refined="<<refinedcap<<" coarse="<<coarsecap<<"\n";
            exit(75);
        }
        if(refinedcap)refined.add(i,h+j,refinedcap);
    }
    for(int j=0;j<k;++j){
        int cap=types[j].n*types[j].P;
        coarse.add(h+j,BT,cap);refined.add(h+j,BT,cap);
    }
    int coarseflow=coarse.flow(BS,BT);
    int refinedflow=refined.flow(BS,BT);
    if(refinedflow>coarseflow){
        cerr<<"CCBAND_FLOW_EXCEEDS_COARSE refined="<<refinedflow<<" coarse="<<coarseflow<<"\n";
        exit(76);
    }

    vector<int> pv,yv;
    long long exactcap=0;
    map<pair<int,int>,array<int,2>> crossing_blocks;
    for(int j=0;j<k;++j){
        int incoming=0;
        for(int t=0;t<k;++t)if(selected[t]&&compat_hall_type(types[t],types[j])) incoming+=types[t].n;
        if(selected[j]) --incoming;
        if(incoming<0){cerr<<"LAYER_NEGATIVE_INCOMING\n";exit(78);}
        exactcap += 1LL*types[j].n*min(types[j].P,incoming);
        for(int z=0;z<types[j].n;++z){pv.push_back(types[j].P);yv.push_back(incoming);}
        int preincoming=incoming+(selected[j]?1:0);
        auto &blk=crossing_blocks[{types[j].q,preincoming}];
        if(selected[j] && types[j].P>=preincoming) blk[0]+=types[j].n;
        if(!selected[j] && types[j].P<preincoming) blk[1]+=types[j].n;
    }
    if(exactcap>=demand){
        cerr<<"LAYER_CANONICAL_WITNESS_NOT_DEFICIENT exactcap="<<exactcap<<" demand="<<demand<<"\n";
        exit(79);
    }
    sort(pv.begin(),pv.end(),greater<int>());
    sort(yv.begin(),yv.end(),greater<int>());
    long long layerupper=0;
    for(int z=0;z<(int)pv.size();++z) layerupper+=min(pv[z],yv[z]);
    if(layerupper<exactcap){cerr<<"LAYER_UPPER_BELOW_EXACT\n";exit(80);}
    int crossing=0;
    for(auto const&kv:crossing_blocks) crossing+=min(kv.second[0],kv.second[1]);
    long long qlayerupper=exactcap+crossing;
    if(qlayerupper>layerupper){cerr<<"QCROSS_Q_UPPER_EXCEEDS_GLOBAL\n";exit(82);}
    return {coarseflow,refinedflow,demand,h,(int)exactcap,(int)layerupper,crossing,(int)qlayerupper};
}

static pair<int,long long> target_cost_flow(const vector<int>&q,const vector<int>&rho,const OD&o,int Q){
    int n=q.size(),S=2*n,T=S+1;MinCostFlow F(T+1);
    for(int i=0;i<n;++i)F.add(S,i,q[i],0);
    for(int i=0;i<n;++i)for(int j=0;j<n;++j)if(o.D[i][j])F.add(i,n+j,1,0);
    for(int j=0;j<n;++j){
        int freecap=min(max(0,o.P[j]),max(0,rho[j]-1));
        if(freecap)F.add(n+j,T,freecap,0);
        int paid=max(0,o.P[j]-freecap);if(paid)F.add(n+j,T,paid,q[j]);
    }
    return F.flow(S,T,Q);
}

struct Result {
    long long profiles=0,paircap_fail=0,incidence_fail=0,pairhall_fail=0,targethall_fail=0,cost_fail=0;
    long long paircap_pass=0,incidence_pass=0,pairhall_pass=0,targethall_pass=0;
    array<long long,10> target_genhist{}; int target_maxgen=0;
    long long band_fail=0,band_pass=0; array<long long,10> band_fail_genhist{}; int band_maxgen=0;
    long long ccband_fail=0,ccband_pass=0;
    long long layer_fail=0,layer_pass=0; long long layer_excess_sum=0; int layer_max_excess=0;
    long long qlayer_fail=0,qlayer_pass=0,qcross_zero=0,qcross_positive=0,qcross_sum=0; array<long long,10> qcross_hist{}; int qcross_max=0;
    bool survives=false;int witness_E=-1;long long witness_cost=-1,witness_envelope=-1;vector<int>wq,wrho;
    int Emax=-1;double seconds=0;
};

struct Scanner {
    const State&st;int S,Emax;vector<Cls>cls;vector<int>suffix;Result res;bool stop=false;
    explicit Scanner(const State&s):st(s){
        S=accumulate(st.s.begin(),st.s.end(),0);map<int,int>ct;for(int r:st.rho)++ct[r];
        for(auto [rho,cnt]:ct){int labels=count_if(st.s.begin(),st.s.end(),[&](int d){return d<=rho;});cls.push_back({rho,cnt,max(0,min(st.a-rho,labels))});}
        suffix.assign(cls.size()+1,0);for(int i=(int)cls.size()-1;i>=0;--i)suffix[i]=suffix[i+1]+cls[i].cnt*cls[i].qmax;
        int U=accumulate(st.rho.begin(),st.rho.end(),0)+st.b*(st.b-st.a-1);
        int Qmax=min({suffix[0],U,st.b*(st.b-1)/2});Emax=Qmax-S;res.Emax=Emax;
    }
    void eval(int E,const vector<int>&q,const vector<int>&rho,long long envelope){
        ++res.profiles;int Q=S+E;
        OD o=pair_capacity(st,q,rho,E);
        if(!o.pass){++res.paircap_fail;return;}++res.paircap_pass;
        if(!variable_incidence(st,q,rho)){++res.incidence_fail;return;}++res.incidence_pass;
        if(pair_flow(q,o)<Q){++res.pairhall_fail;return;}++res.pairhall_pass;
        auto [f,cost]=target_cost_flow(q,rho,o,Q);
        if(f<Q){
            ++res.targethall_fail;
            auto [qflow,gcount]=canonical_antichain_stats(q,o,Q);
            if(qflow!=f){cerr<<"ANTICHAIN_FLOW_MISMATCH state="<<st.id<<" E="<<E<<" labelled="<<f<<" quotient="<<qflow<<"\n";exit(6);}
            int bin=min(gcount,9);++res.target_genhist[bin];res.target_maxgen=max(res.target_maxgen,gcount);
            auto [bflow,ccflow,bdemand,bgen,bexact,layerupper,qcross,qlayerupper]=canonical_band_flows(q,o,Q);
            if(bgen!=gcount){cerr<<"BAND_GENERATOR_COUNT_MISMATCH state="<<st.id<<" E="<<E<<" antichain="<<gcount<<" band="<<bgen<<"\n";exit(11);}
            if(bexact>=bdemand){cerr<<"LAYER_EXACT_MARGIN_SIGN_FAILURE state="<<st.id<<" E="<<E<<"\n";exit(81);}
            res.band_maxgen=max(res.band_maxgen,bgen);
            if(bflow<bdemand){++res.band_fail;++res.band_fail_genhist[min(bgen,9)];}
            else ++res.band_pass;
            if(ccflow<bdemand)++res.ccband_fail;
            else ++res.ccband_pass;
            if(layerupper<bdemand)++res.layer_fail;
            else {++res.layer_pass; int ex=layerupper-bdemand; res.layer_excess_sum+=ex; res.layer_max_excess=max(res.layer_max_excess,ex);}
            if(qlayerupper<bdemand)++res.qlayer_fail; else ++res.qlayer_pass;
            if(qcross==0)++res.qcross_zero; else ++res.qcross_positive;
            res.qcross_sum+=qcross; res.qcross_max=max(res.qcross_max,qcross); ++res.qcross_hist[min(qcross,9)];
            if(bflow<bdemand && ccflow>=bdemand){
                cerr<<"CCBAND_MONOTONICITY_FAILURE state="<<st.id<<" E="<<E<<" coarse="<<bflow<<" refined="<<ccflow<<" demand="<<bdemand<<"\n";
                exit(77);
            }
            return;
        }++res.targethall_pass;
        if(envelope>=0&&cost>envelope){++res.cost_fail;return;}
        res.survives=true;res.witness_E=E;res.witness_cost=cost;res.witness_envelope=envelope;res.wq=q;res.wrho=rho;stop=true;
    }
    void rec(int ci,int used,int Q,int E,long long envelope,vector<int>&q,vector<int>&rho){
        if(stop)return;
        if(ci==(int)cls.size()){if(used==Q)eval(E,q,rho,envelope);return;}
        auto C=cls[ci];int lo=max(0,Q-used-suffix[ci+1]),hi=min(C.cnt*C.qmax,Q-used);if(lo>hi)return;
        vector<int>sums;for(int sm=lo;sm<=hi;++sm)if(!parts(C.cnt,C.qmax,sm).empty())sums.push_back(sm);
        int rem=0;for(int j=ci;j<(int)cls.size();++j)rem+=cls[j].cnt;
        double tgt=rem?(double)(Q-used)*C.cnt/rem:0.0;
        stable_sort(sums.begin(),sums.end(),[&](int x,int y){return abs(x-tgt)<abs(y-tgt);});
        for(int sm:sums)for(auto const&pv:parts(C.cnt,C.qmax,sm)){
            size_t old=q.size();q.insert(q.end(),pv.begin(),pv.end());rho.insert(rho.end(),C.cnt,C.rho);
            rec(ci+1,used+sm,Q,E,envelope,q,rho);q.resize(old);rho.resize(old);if(stop)return;
        }
    }
    Result run(){
        auto t0=chrono::steady_clock::now();vector<int>q,rho;
        if(Emax>=0)for(int E=0;E<=Emax&&!stop;++E){
            long long env=excess_envelope(st,E);
            if(env==-(1LL<<50))continue; // no excess distribution can realize E
            rec(0,0,S+E,E,env,q,rho);
        }
        res.seconds=chrono::duration<double>(chrono::steady_clock::now()-t0).count();return res;
    }
};

static string vs(const vector<int>&v){ostringstream o;for(size_t i=0;i<v.size();++i){if(i)o<<',';o<<v[i];}return o.str();}

int main(int argc,char**argv){
    if(argc<3){cerr<<"usage: scan_post_pair_relational INPUT OUTPUT.tsv\n";return 2;}
    ifstream in(argv[1]);ofstream out(argv[2]);if(!in||!out)return 2;int N;in>>N;
    out<<"layer\tstate_id\tS\tEmax\tprofiles_tested\tpaircap_fail\tpaircap_pass\tincidence_fail\tincidence_pass\tpairhall_fail\tpairhall_pass\ttargethall_fail\ttargethall_pass\ttarget_gen1\ttarget_gen2\ttarget_gen3\ttarget_gen4\ttarget_gen5\ttarget_gen6\ttarget_gen7\ttarget_gen8\ttarget_gen9plus\ttarget_maxgen\tband_fail\tband_pass\tband_fail_gen1\tband_fail_gen2\tband_fail_gen3\tband_fail_gen4\tband_fail_gen5\tband_fail_gen6\tband_fail_gen7\tband_fail_gen8\tband_fail_gen9plus\tband_maxgen\tccband_fail\tccband_pass\tlayer_fail\tlayer_pass\tlayer_excess_sum\tlayer_max_excess\tqlayer_fail\tqlayer_pass\tqcross_zero\tqcross_positive\tqcross_sum\tqcross_max\tqcross_0\tqcross_1\tqcross_2\tqcross_3\tqcross_4\tqcross_5\tqcross_6\tqcross_7\tqcross_8\tqcross_9plus\tcost_fail\tstatus\twitness_E\twitness_cost\twitness_envelope\tseconds\twitness_rho\twitness_q\n";
    int excluded=0,survived=0;long long profiles=0;
    for(int z=0;z<N;++z){
        State st;int ns,nr;in>>st.layer>>st.id>>st.a>>st.b>>st.t>>ns;st.s.resize(ns);for(int&x:st.s)in>>x;in>>nr;st.rho.resize(nr);for(int&x:st.rho)in>>x;
        Scanner sc(st);Result r=sc.run();string status=r.survives?"SURVIVES_RELATIONAL":"RELATIONAL_EXCLUDED";if(r.survives)++survived;else++excluded;profiles+=r.profiles;
        out<<st.layer<<'\t'<<st.id<<'\t'<<accumulate(st.s.begin(),st.s.end(),0)<<'\t'<<r.Emax<<'\t'<<r.profiles<<'\t'
           <<r.paircap_fail<<'\t'<<r.paircap_pass<<'\t'<<r.incidence_fail<<'\t'<<r.incidence_pass<<'\t'
           <<r.pairhall_fail<<'\t'<<r.pairhall_pass<<'\t'<<r.targethall_fail<<'\t'<<r.targethall_pass<<'\t'
           <<r.target_genhist[1]<<'\t'<<r.target_genhist[2]<<'\t'<<r.target_genhist[3]<<'\t'<<r.target_genhist[4]<<'\t'
           <<r.target_genhist[5]<<'\t'<<r.target_genhist[6]<<'\t'<<r.target_genhist[7]<<'\t'<<r.target_genhist[8]<<'\t'
           <<r.target_genhist[9]<<'\t'<<r.target_maxgen<<'\t'<<r.band_fail<<'\t'<<r.band_pass<<'\t'
           <<r.band_fail_genhist[1]<<'\t'<<r.band_fail_genhist[2]<<'\t'<<r.band_fail_genhist[3]<<'\t'<<r.band_fail_genhist[4]<<'\t'
           <<r.band_fail_genhist[5]<<'\t'<<r.band_fail_genhist[6]<<'\t'<<r.band_fail_genhist[7]<<'\t'<<r.band_fail_genhist[8]<<'\t'
           <<r.band_fail_genhist[9]<<'\t'<<r.band_maxgen<<'\t'<<r.ccband_fail<<'\t'<<r.ccband_pass<<'\t'<<r.layer_fail<<'\t'<<r.layer_pass<<'\t'<<r.layer_excess_sum<<'\t'<<r.layer_max_excess<<'\t'<<r.qlayer_fail<<'\t'<<r.qlayer_pass<<'\t'<<r.qcross_zero<<'\t'<<r.qcross_positive<<'\t'<<r.qcross_sum<<'\t'<<r.qcross_max<<'\t'<<r.qcross_hist[0]<<'\t'<<r.qcross_hist[1]<<'\t'<<r.qcross_hist[2]<<'\t'<<r.qcross_hist[3]<<'\t'<<r.qcross_hist[4]<<'\t'<<r.qcross_hist[5]<<'\t'<<r.qcross_hist[6]<<'\t'<<r.qcross_hist[7]<<'\t'<<r.qcross_hist[8]<<'\t'<<r.qcross_hist[9]<<'\t'<<r.cost_fail<<'\t'
           <<status<<'\t'<<r.witness_E<<'\t'<<r.witness_cost<<'\t'<<r.witness_envelope<<'\t'<<r.seconds<<'\t'<<vs(r.wrho)<<'\t'<<vs(r.wq)<<'\n';
        cerr<<"state "<<st.id<<" "<<status<<" E="<<r.witness_E<<" profiles="<<r.profiles<<" pairpass="<<r.paircap_pass<<" incpass="<<r.incidence_pass<<" sec="<<r.seconds<<"\n";
    }
    cerr<<"SUMMARY states="<<N<<" relational_excluded="<<excluded<<" survives="<<survived<<" profiles="<<profiles<<"\n";
}
