#!/usr/bin/env python3
"""Exact finite collision diagnostic for the n=29 t=2,3 regime frontiers.

Inputs are the demands.json and row_survivors.txt files regenerated by
project/reviews/n29/2026-09-08-redteam-restart-v1/minimal_prepare.py and
minimal_rows.cpp.

The script does not re-prove the template gaps.  It consumes the deterministic
regime assignments already established by the exact t=2 and t=3 template
replays and tests whether coarse profile statistics separate those labels.
"""
from __future__ import annotations
from argparse import ArgumentParser
from collections import Counter, defaultdict
from pathlib import Path
import json


def load(demands_json: Path, rows: Path, t: int):
    D=json.loads(demands_json.read_text())
    out=[]
    for line in rows.read_text().splitlines():
        if not line.strip():
            continue
        z=list(map(int,line.split()))
        did=z[0]; rho=z[2:]; s=D[did]["s"]
        if min(s)>0 and sum(s)==sum(rho)+2*t:
            out.append({"index":len(out),"demand_id":did,"s":s,"rho":rho})
    return out


def h_res(rho):
    h=0
    for k,x in enumerate(sorted(rho,reverse=True),1):
        if x>=k: h=k
        else: break
    return h


def initial_caps(s,rho):
    return [min(12-r,sum(x<=r for x in s)) for r in rho]


def cutoff_L(s,rho):
    C=initial_caps(s,rho)
    Z=[r+c for r,c in zip(rho,C)]
    L=0
    for k in range(1,max(C,default=0)+1):
        if sum(z>=k-1 for z in Z)>=k+1:
            L=k
        else:
            break
    return L


def nu1(p): return p["s"].count(1)
def rho1(p): return p["rho"].count(1)
def G(p): return 2*rho1(p)+nu1(p)


def label_t2(p):
    n=nu1(p)
    if n==2: return "T0"
    if n==1: return "T1"
    if n==0: return "T2"
    raise ValueError(f"unexpected t=2 nu1={n} at profile {p['index']}")


def label_t3(p):
    r1=rho1(p); s5=p["s"].count(5); s1=nu1(p)
    if r1<=8:
        return "A530" if s5==0 else "A38"
    return "A1" if s1==0 else "A0"


def key_hL(p):
    return (h_res(p["rho"]),cutoff_L(p["s"],p["rho"]))


def census(P,label_fn,key_fn):
    d=defaultdict(Counter)
    examples=defaultdict(list)
    for p in P:
        k=key_fn(p); lab=label_fn(p)
        d[k][lab]+=1
        if len(examples[k])<8: examples[k].append(p["index"])
    rows=[]
    for k in sorted(d):
        rows.append({
            "key":list(k) if isinstance(k,tuple) else k,
            "profiles":sum(d[k].values()),
            "labels":dict(sorted(d[k].items())),
            "mixed":len(d[k])>1,
            "example_indices":examples[k],
        })
    return rows


def mixed_summary(rows):
    m=[r for r in rows if r["mixed"]]
    return {"cells":len(m),"profiles":sum(r["profiles"] for r in m)}


def linear_test(P,label_fn,a,b):
    rows=census(P,label_fn,lambda p:key_hL(p)+(a*rho1(p)+b*nu1(p),))
    return mixed_summary(rows)


def first_by_label(P,label_fn,target_hL):
    ans={}
    for p in P:
        if key_hL(p)!=target_hL: continue
        lab=label_fn(p)
        if lab not in ans:
            ans[lab]={
                "index":p["index"],"demand_id":p["demand_id"],
                "rho1":rho1(p),"nu1":nu1(p),"G":G(p),
                "s":p["s"],"rho":p["rho"],
            }
    return ans


def main():
    ap=ArgumentParser()
    ap.add_argument("--t2-demands-json",type=Path,required=True)
    ap.add_argument("--t2-rows",type=Path,required=True)
    ap.add_argument("--t3-demands-json",type=Path,required=True)
    ap.add_argument("--t3-rows",type=Path,required=True)
    ap.add_argument("--output",type=Path,required=True)
    z=ap.parse_args()

    P2=load(z.t2_demands_json,z.t2_rows,2)
    P3=load(z.t3_demands_json,z.t3_rows,3)
    if len(P2)!=902: raise SystemExit(f"expected 902 t=2 profiles, got {len(P2)}")
    if len(P3)!=94: raise SystemExit(f"expected 94 t=3 profiles, got {len(P3)}")

    hL2=census(P2,label_t2,key_hL)
    hL3=census(P3,label_t3,key_hL)
    hLG2=census(P2,label_t2,lambda p:key_hL(p)+(G(p),))
    hLG3=census(P3,label_t3,lambda p:key_hL(p)+(G(p),))

    small_linear={}
    for a,b in [(1,0),(0,1),(1,1),(1,2),(2,1)]:
        small_linear[f"{a},{b}"]={
            "statistic":f"{a}*rho1+{b}*nu1",
            "t2":linear_test(P2,label_t2,a,b),
            "t3":linear_test(P3,label_t3,a,b),
        }

    triangle=[]
    for i in [0,3,77]:
        p=P2[i]
        triangle.append({
            "index":i,"label":label_t2(p),"demand_id":p["demand_id"],
            "h_res":h_res(p["rho"]),"L":cutoff_L(p["s"],p["rho"]),
            "rho1":rho1(p),"nu1":nu1(p),"G":G(p),
        })

    ok=(
        mixed_summary(hL2)["cells"]>0 and
        mixed_summary(hL3)["cells"]>0 and
        mixed_summary(hLG2)["cells"]==0 and
        mixed_summary(hLG3)["cells"]==0 and
        all((x["h_res"],x["L"])==(4,6) for x in triangle) and
        small_linear["2,1"]["t2"]["cells"]==0 and
        small_linear["2,1"]["t3"]["cells"]==0
    )
    out={
        "schema":"n29-t23-hL-compression-falsification-v1",
        "status":"PASS" if ok else "FAIL",
        "scope":{"n":29,"Delta":16,"t2_profiles":len(P2),"t3_profiles":len(P3)},
        "definitions":{
            "h_res":"max{k: #{u:rho_u>=k}>=k}",
            "L":"max{k>=1: #{u:rho_u+C_u>=k-1}>=k+1}, C_u=min(12-rho_u,#{i:s_i<=rho_u})",
            "G":"2*#{u:rho_u=1}+#{i:s_i=1}",
        },
        "hL":{
            "t2":{"summary":mixed_summary(hL2),"cells":hL2},
            "t3":{"summary":mixed_summary(hL3),"cells":hL3},
        },
        "hLG":{
            "t2":{"summary":mixed_summary(hLG2),"cells":hLG2},
            "t3":{"summary":mixed_summary(hLG3),"cells":hLG3},
        },
        "t2_lower_bound_triangle":triangle,
        "first_hL_4_6_profile_by_label":{
            "t2":first_by_label(P2,label_t2,(4,6)),
            "t3":first_by_label(P3,label_t3,(4,6)),
        },
        "small_nonnegative_primitive_linear_comparison":small_linear,
        "interpretation":"(h_res,L) is exactly falsified as a regime key on both complete finite frontiers; adding G=2*rho1+nu1 makes every occupied cell regime-pure on both. This is a finite structural diagnostic, not a general-N theorem.",
    }
    z.output.parent.mkdir(parents=True,exist_ok=True)
    z.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n")
    print(json.dumps(out,indent=2,sort_keys=True))
    if not ok: raise SystemExit(1)


if __name__=="__main__":
    main()
