#!/usr/bin/env python3
"""Generate a diagnostic-only scanner for the unique staircase-band false negative.

Run make_antichain_stats_scanner.py and make_band_reach_scanner.py first.  This
script does not alter any mathematical pass/fail decision.  It augments the
band-reach scanner so that every exact target-Hall failure which nevertheless
passes the staircase-band relaxation emits a complete, replayable description:
state/E/Q, exact quotient flow and band flow, the (q,c,rho,P,n) type table,
canonical maximal minimum-cut membership, generator indices, band assignment,
and exact-vs-generator compatibility for every selected source type/target type.

Reconnaissance only.  No whole-state closure is promoted by this script.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "scan_band_reach_stats.cpp"
OUT = HERE / "scan_band_exception_diagnostic.cpp"
s = SRC.read_text()

old = "static tuple<int,int,int> canonical_band_flow(const vector<int>&q,const OD&o,int Q){"
new = "static tuple<int,int,int> canonical_band_flow(const vector<int>&q,const OD&o,int Q,int state_id,int E){"
if s.count(old) != 1:
    raise SystemExit("canonical_band_flow signature not unique")
s = s.replace(old, new, 1)

old = "            auto [bflow,bdemand,bgen]=canonical_band_flow(q,o,Q);"
new = "            auto [bflow,bdemand,bgen]=canonical_band_flow(q,o,Q,st.id,E);"
if s.count(old) != 1:
    raise SystemExit("canonical_band_flow call not unique")
s = s.replace(old, new, 1)

needle = "    int bandflow=B.flow(BS,BT);\n    return {bandflow,demand,h};"
if s.count(needle) != 1:
    raise SystemExit("bandflow return point not unique")

block = r'''    int bandflow=B.flow(BS,BT);

    // Emit the complete object only for a false negative of the band relaxation.
    // The pilot currently has exactly one such profile, in state 226, but the
    // diagnostic is deliberately generic and will expose any future discrepancy.
    if(exactflow<Q && bandflow>=demand){
        cerr<<"BAND_EXCEPTION_BEGIN state="<<state_id<<" E="<<E<<" Q="<<Q
            <<" exactflow="<<exactflow<<" exact_deficit="<<(Q-exactflow)
            <<" bandflow="<<bandflow<<" band_demand="<<demand
            <<" band_slack="<<(bandflow-demand)<<" generators="<<h<<"\n";
        cerr<<"TYPE_HEADER idx q c rho P n selected band generator\n";
        vector<unsigned char> isgen(k,0);for(int g:gens)isgen[g]=1;
        for(int t=0;t<k;++t){
            cerr<<"TYPE "<<t<<' '<<types[t].q<<' '<<types[t].c<<' '
                <<(types[t].c-types[t].q)<<' '<<types[t].P<<' '<<types[t].n<<' '
                <<int(selected[t])<<' '<<band[t]<<' '<<int(isgen[t])<<"\n";
        }
        cerr<<"GENERATOR_ORDER";for(int i=0;i<h;++i)cerr<<' '<<gens[i];cerr<<"\n";
        cerr<<"BAND_HEADER band generator M D\n";
        for(int i=0;i<h;++i)cerr<<"BAND "<<i<<' '<<gens[i]<<' '<<M[i]<<' '<<D[i]<<"\n";
        cerr<<"COMPAT_HEADER source_type target_type exact generator band selected_source\n";
        for(int x=0;x<k;++x)if(selected[x]){
            int bi=band[x];
            for(int y=0;y<k;++y){
                bool ex=compat_hall_type(types[x],types[y]);
                bool ge=compat_hall_type(types[gens[bi]],types[y]);
                cerr<<"COMPAT "<<x<<' '<<y<<' '<<int(ex)<<' '<<int(ge)<<' '<<bi<<" 1\n";
            }
        }
        // Quantify precisely how much edge capacity the band relaxation adds
        // relative to the selected exact type system, target by target.
        cerr<<"TARGET_HEADER target_type target_capacity exact_incoming band_incoming overestimate\n";
        for(int y=0;y<k;++y){
            long long exact_in=0,band_in=0;
            for(int x=0;x<k;++x)if(selected[x]&&compat_hall_type(types[x],types[y])){
                exact_in += 1LL*types[x].n*types[y].n;
                if(x==y) exact_in -= types[x].n;
            }
            for(int i=0;i<h;++i)if(compat_hall_type(types[gens[i]],types[y])){
                long long copies=M[i]-(selected[y]&&band[y]==i?1:0);
                band_in += copies*types[y].n;
            }
            cerr<<"TARGET "<<y<<' '<<(types[y].n*types[y].P)<<' '<<exact_in<<' '
                <<band_in<<' '<<(band_in-exact_in)<<"\n";
        }
        cerr<<"BAND_EXCEPTION_END state="<<state_id<<" E="<<E<<"\n";
    }
    return {bandflow,demand,h};'''
s = s.replace(needle, block, 1)

banner = r'''/* GENERATED by make_band_exception_diagnostic.py after the two standard
   generators.  Diagnostic instrumentation only: mathematical decisions are
   unchanged, and no state is promoted by this program. */
'''
OUT.write_text(banner + s)
print(OUT)
