#!/usr/bin/env python3
"""Generate a principal-hardness-upset reach scanner from the frozen single-type scanner.

The transformation is intentionally small and checked.  It preserves the same
state/q-profile enumeration and all earlier/later screens; only the cheap Hall
pre-screen is changed from a singleton complete type to the principal hardness
up-set generated by one type.
"""
from pathlib import Path
import re

HERE = Path(__file__).resolve().parent
src_path = HERE / "scan_single_type_hall_reach.cpp"
out_path = HERE / "scan_principal_upset_hall_reach.cpp"
s = src_path.read_text()

pattern = re.compile(
    r"static int single_type_hall_deficit\(const vector<int>&q,const OD&o\)\{.*?\n\}\n\nstatic pair<int,long long> target_cost_flow",
    re.S,
)
replacement = r'''static int principal_upset_hall_deficit(const vector<int>&q,const OD&o){
    map<tuple<int,int,int>,int> ct;
    for(int i=0;i<(int)q.size();++i)++ct[make_tuple(q[i],o.c[i],o.P[i])];
    vector<HallType> types;types.reserve(ct.size());
    for(auto const&kv:ct){auto [qq,cc,pp]=kv.first;types.push_back({qq,cc,pp,kv.second});}
    int best=0;
    for(int g=0;g<(int)types.size();++g){
        auto const&G=types[g];
        vector<unsigned char> in(types.size(),0);
        long long L=0,R=0;
        for(int a=0;a<(int)types.size();++a){
            auto const&A=types[a];
            if(A.q>=G.q && A.c<=G.c && A.P>=G.P){
                in[a]=1;
                L+=1LL*A.n*A.q;
            }
        }
        for(int b=0;b<(int)types.size();++b){
            auto const&B=types[b];
            int incoming=0;
            for(int a=0;a<(int)types.size();++a)if(in[a]&&compat_type(types[a],B))incoming+=types[a].n;
            if(in[b])--incoming; // delete each target's own source copy
            assert(incoming>=0);
            R+=1LL*B.n*min(B.P,incoming);
        }
        if(L>R)best=max(best,(int)(L-R));
    }
    return best;
}

static pair<int,long long> target_cost_flow'''
s2, n = pattern.subn(replacement, s, count=1)
if n != 1:
    raise SystemExit(f"expected exactly one single-type function block, replaced {n}")

repls = {
    "single_type_hall_deficit": "principal_upset_hall_deficit",
    "singletype_fail": "principal_fail",
    "singletype_pass": "principal_pass",
    "max_single_deficit": "max_principal_deficit",
    "singlefail=": "principalfail=",
    "single-type Hall": "principal-upset Hall",
    "single type": "principal up-set",
    "single-type": "principal-upset",
}
for old, new in repls.items():
    s2 = s2.replace(old, new)

banner = '''/* GENERATED by make_principal_upset_scanner.py from scan_single_type_hall_reach.cpp.
   The only mathematical change is the Hall pre-screen: each generator type g
   is replaced by its full hardness up-set {a:q_a>=q_g,c_a<=c_g,P_a>=P_g}. */
'''
s2 = banner + s2
out_path.write_text(s2)
print(out_path)
