#!/usr/bin/env python3
from pathlib import Path
import subprocess

README = Path("README.md")
STATE = Path("CURRENT_STATE.md")
AUDIT = Path("project/research/general_n/2026-09-14-source-sharing-v1/CI_AUDIT.md")
RESTORE = Path("tools/restore_source_price_publication.py")
RESTORE_WF = Path(".github/workflows/restore-source-price-publication.yml")
SELF = Path("tools/_apply_attribution_provenance_fix.py")
SELF_WF = Path(".github/workflows/_attribution-provenance-fix.yml")

def replace_once(path, old, new):
    text = path.read_text()
    if text.count(old) != 1:
        raise RuntimeError(f"{path}: expected exactly one target, found {text.count(old)}")
    path.write_text(text.replace(old, new, 1))

# Both live status blocks must change in this same commit.
readme_anchor = "| Documentation/process guards | Every commit must pair README/CURRENT_STATE updates. Historical N30 navigation failure, red-team-history guard failure and standalone row471 paired-status process failure remain visible rather than repainted green |\n| Active continuation |"
readme_row = "| Documentation/process guards | Every commit must pair README/CURRENT_STATE updates. Historical N30 navigation failure, red-team-history guard failure and standalone row471 paired-status process failure remain visible rather than repainted green |\n| Commit-attribution provenance | Historical commit `aa6c41fcede3bf2e7e935a00840030ef0b9ee1df` was created by restoration run `34905883642`, whose actor and triggering actor were `paullenz`; its script used synthetic identity `Research verification <verification@users.noreply.github.com>`, which GitHub mapped to account `verification` (display name Bill Wang). The commit is retained without history rewrite; the one-off workflow is now manual-only and future workflow-created commits use canonical `github-actions[bot]`. Mathematical/canonical status unchanged. |\n| Active continuation |"
replace_once(README, readme_anchor, readme_row)

readme_checkpoint = "**Mathematical/canonical status is unchanged: 4,626 exclusions / 952 survivors / 3,632 whole-state closures. No forced-core closure is promoted by this checkpoint.** External mathematical review remains OPEN.\n<!-- RELATIONAL-FULL-PROMOTION:PROMOTED -->"
readme_prov = "**Mathematical/canonical status is unchanged: 4,626 exclusions / 952 survivors / 3,632 whole-state closures. No forced-core closure is promoted by this checkpoint.** External mathematical review remains OPEN.\n\n**Maintenance provenance correction — 15 September 2026.** Commit `aa6c41fcede3bf2e7e935a00840030ef0b9ee1df` was generated by successful restoration workflow run `34905883642`. GitHub records both the run actor and triggering actor as `paullenz`; the workflow script nevertheless configured the Git commit as `Research verification <verification@users.noreply.github.com>`, which GitHub mapped to the unrelated account `verification` (display name Bill Wang). That historical commit is preserved to avoid rewriting the audited chain. The one-off restoration workflow is now manual-only, completed replays are read-only, and any future workflow-created commit uses the canonical `github-actions[bot]` identity. **Mathematical and canonical status are unchanged.**\n<!-- RELATIONAL-FULL-PROMOTION:PROMOTED -->"
replace_once(README, readme_checkpoint, readme_prov)

state_anchor = "**Mathematical/canonical status is unchanged: 4,626 exclusions / 952 survivors / 3,632 whole-state closures. No forced-core closure is promoted by this checkpoint.** External review remains OPEN.\n<!-- RELATIONAL-FULL-PROMOTION:PROMOTED -->"
state_prov = "**Mathematical/canonical status is unchanged: 4,626 exclusions / 952 survivors / 3,632 whole-state closures. No forced-core closure is promoted by this checkpoint.** External review remains OPEN.\n\n**Maintenance provenance correction — 15 September 2026.** Historical commit `aa6c41fcede3bf2e7e935a00840030ef0b9ee1df` came from successful restoration run `34905883642`; GitHub records `paullenz` as both actor and triggering actor. The restoration script set synthetic author/committer `Research verification <verification@users.noreply.github.com>`, which GitHub mapped to account `verification` (display name Bill Wang). This is an attribution error, not evidence that that account triggered the workflow. The commit is retained without rewriting the audited chain; the one-off workflow is now manual-only, completed replays make no repository mutation, and future workflow-created commits use canonical `github-actions[bot]`. **Mathematical/canonical status unchanged.**\n<!-- RELATIONAL-FULL-PROMOTION:PROMOTED -->"
replace_once(STATE, state_anchor, state_prov)

audit_note = """
## Commit-attribution provenance correction, 2026-09-15

Commit `aa6c41fcede3bf2e7e935a00840030ef0b9ee1df` was produced by successful restoration run `34905883642`. GitHub records both the workflow actor and triggering actor as `paullenz`, while `tools/restore_source_price_publication.py` explicitly configured the Git commit as `Research verification <verification@users.noreply.github.com>`. GitHub mapped that noreply identity to account `verification` (display name Bill Wang), creating misleading contributor attribution. This is a synthetic-identity metadata error, not evidence that account `verification` triggered the workflow.

The historical commit is deliberately retained to avoid rewriting the audited commit chain. The restoration workflow is now manual-only, the completed-restoration path replays and exits without repository mutation, and any future workflow-created commit uses GitHub's canonical Actions identity `github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>`. Mathematical scope, expected hashes, verifier results and canonical status are unchanged.
"""
audit_text = AUDIT.read_text()
if "## Commit-attribution provenance correction, 2026-09-15" in audit_text:
    raise RuntimeError("audit provenance note already present")
AUDIT.write_text(audit_text.rstrip() + "\n\n" + audit_note.strip() + "\n")

# Stage only non-workflow target files. Temporary setup files remain on this staging branch;
# they are deliberately excluded from the eventual main-tree commit.
subprocess.run(["git", "add", "README.md", "CURRENT_STATE.md", str(AUDIT), str(RESTORE)], check=True)
subprocess.run(["git", "-c", "user.name=github-actions[bot]",
                "-c", "user.email=41898282+github-actions[bot]@users.noreply.github.com",
                "commit", "-m", "Correct workflow attribution provenance without rewriting history"], check=True)
# This final commit itself is the one that must satisfy the paired-status rule.
parent = subprocess.check_output(["git", "rev-parse", "HEAD^"], text=True).strip()
subprocess.run(["python3", "scripts/check_status_sync.py", "--base", parent, "--head", "HEAD"], check=True)
subprocess.run(["git", "push", "origin", "HEAD:maintenance/attribution-provenance-20260915"], check=True)
