#!/usr/bin/env python3
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether

ROOT=Path(__file__).resolve().parents[4]
OUT=ROOT/'output/pdf/Erdos742_Daily_Red_Team_Audit_2026-09-23.pdf'
OUT.parent.mkdir(parents=True,exist_ok=True)

navy=colors.HexColor('#17324D'); blue=colors.HexColor('#2E6F9E'); pale=colors.HexColor('#EAF2F8')
red=colors.HexColor('#9E2A2B'); amber=colors.HexColor('#A45A00'); grey=colors.HexColor('#5D6873')
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='Title2',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=21,leading=25,textColor=navy,spaceAfter=8))
styles.add(ParagraphStyle(name='Sub',parent=styles['Normal'],fontSize=9.3,leading=13,textColor=grey,spaceAfter=12))
styles.add(ParagraphStyle(name='H1x',parent=styles['Heading1'],fontName='Helvetica-Bold',fontSize=14,leading=17,textColor=navy,spaceBefore=10,spaceAfter=6))
styles.add(ParagraphStyle(name='H2x',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=11,leading=14,textColor=blue,spaceBefore=7,spaceAfter=4))
styles.add(ParagraphStyle(name='Bodyx',parent=styles['BodyText'],fontSize=9.3,leading=13.2,spaceAfter=6))
styles.add(ParagraphStyle(name='Smallx',parent=styles['BodyText'],fontSize=7.4,leading=9.3,spaceAfter=2))
styles.add(ParagraphStyle(name='Callout',parent=styles['BodyText'],fontSize=10,leading=14,leftIndent=8,rightIndent=8,spaceBefore=4,spaceAfter=8,textColor=navy,borderColor=blue,borderWidth=.6,borderPadding=7,backColor=pale))

def P(text,style='Bodyx'): return Paragraph(text,styles[style])
def header_footer(canvas,doc):
    canvas.saveState(); w,h=A4
    canvas.setStrokeColor(colors.HexColor('#CAD5DF'));canvas.line(18*mm,14*mm,w-18*mm,14*mm)
    canvas.setFont('Helvetica',7.5);canvas.setFillColor(grey)
    canvas.drawString(18*mm,9.5*mm,'Independent Erdos #742 daily adversarial audit - 23 September 2026')
    canvas.drawRightString(w-18*mm,9.5*mm,f'Page {doc.page}')
    canvas.restoreState()

doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=17*mm,leftMargin=17*mm,topMargin=16*mm,bottomMargin=19*mm,title='Independent Erdos #742 Daily Red-Team Audit - 23 September 2026',author='Murty-Simon independent proof programme')
S=[]
S += [P('Independent Erdos #742<br/>Daily adversarial audit','Title2'),P('23 September 2026 | Audited predecessor <b>320ff91c4b3b1c64e98349788f9f971f65a9ef01</b><br/>Independent Murty-Simon proof programme - mathematical and launch-reliability review','Sub')]
S += [P('<b>Disposition.</b> Material progress survives the audit, but the general theorem is not proved. The raw graph-to-profile bridge now has a standalone derivation and an exact finite regression. Internally, the edge bound is supported through total demand <b>S&lt;=13</b> and balanced-complete-bipartite equality through <b>S&lt;=8</b>. The candidate maximum-degree threshold remains <b>250/429</b>; the residual strip and full equality theorem remain open.','Callout')]

S += [P('What changed in the previous 24 hours','H1x')]
data=[['Claim','Audit disposition','Evidence'],
['Raw graph-to-profile bridge','Retained; internally reconstructed','757 D2C graphs; 1,256 roots; 2,722 legal selections; 153 positive-demand selections'],
['Maximum-degree threshold','Unchanged candidate: 250/429','No new lower threshold; prior rational/scalar replay remains current'],
['Zero-demand equality','Retained at internal candidate scope','Both parities; odd K(k,k+1) control preserved'],
['Bounded edge result','Retained through S&lt;=13','r=11 cross-file replay passes after evidence repair'],
['Equality characterization','Retained through S&lt;=8 only','2,103 r=8 equality source populations; zero supplement survivors'],
['r=12 support ten','OPEN','42/6,386 source-feasible kernels; supplement solve unfinished']]
t=Table([[P(str(x),'Smallx') for x in row] for row in data],colWidths=[42*mm,49*mm,76*mm],repeatRows=1)
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#AAB7C4')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F5F8FA')]),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)]));S += [t]

S += [P('Red-team findings','H1x'),P('<b>1. Evidence corruption found and repaired.</b> Two committed files contained truncation-warning text and ellipsis markers: <font name="Courier">R8_EQUALITY_CORE_SCREEN.json</font> and <font name="Courier">r11_support9_masks.txt</font>. The advertised replay initially crashed. The corrupt originals are preserved with <font name="Courier">.corrupted-at-320ff91</font> names; clean outputs were regenerated from <font name="Courier">screen_r8_equality.py</font> and <font name="Courier">r11_support9_orbits.cpp</font>. <font name="Courier">verify_r8_pipeline.py</font> and <font name="Courier">audit_r11_pipeline.py</font> then passed.'),P('<b>2. Residual-free helper asymmetry tested.</b> The earlier r=8 equality checker permits residual-free supplement helpers, while later r=10/r=11 scripts omit them. An exact helper-aware replay reopened none of the four r=10 kernels. An optimistic helper-aware MILP rejected 24/27 r=11 kernels; the other three have only the all-zero free type, which discharges no obligation, so their original exhaustive DFS is unaffected. No stored r=11 witness population reopened.'),P('<b>3. Independence retained.</b> Search and dependency review found no invocation of the external Erdos742/Erdos742 universal e+disj+X inequality in the new raw bridge, equality or bounded-demand chain.'),P('<b>4. Realizability remains distinct.</b> The finite profiles are necessary-condition systems. Infeasible rows can exclude graphs only through the audited bridge; surviving abstract rows are not D2C constructions. The r=11 cross-file audit does not independently reimplement orbit quotienting or source/supplement algorithms.')]

S += [PageBreak(),P('Mathematical audit detail','H1x'),P('Raw criticality and bridge','H2x'),P('The standalone note quantifies over every maximum-degree root and every legal quasi-edge selection. It derives the exact ledger e(F)=r+t, source-demand injection, supplement forcing, threshold capacity and radical profile projection. The a=0 star case is separated correctly, repairing the earlier strict 0&lt;0 display without changing either degree assembly.'),P('Fresh execution of <font name="Courier">check_raw_profile.py</font> passed with source SHA-256 <font name="Courier">138ef5194f134e1902685692285af1f816a18792dbd337439634bfdc3dfbf2d4</font>. Coverage includes 8,374 independent BFS edge-deletion checks and both selected/residual supplement branches. Limit: no positive-surplus actual graph was found and only two high-load threshold instances were exercised.'),P('Equality geometry','H2x'),P('The S=0 proof forces t=r=e(F)=0 at equality. The even case yields K(k,k); the odd maximum-degree and sink argument yields K(k,k+1), including the small endpoint. Repeated Boolean codes are not identified with vertices. Balanced complete bipartite graphs remain positive controls rather than excluded cases.'),P('Finite demand closure','H2x'),P('For a strict counterexample S&gt;=r+2. Exact strict closure through r=11 therefore supports the edge bound through S&lt;=13. The repaired high-support replay contains 2,496, 3,273 and 280 strict rows; source survivors 16, 8 and 3; supplement survivors zero. Equality closure through r=8 supports equality through S&lt;=8. All are internal computer-assisted statements.'),P('Remaining mathematical holes','H2x'),P('The 42 source-feasible r=12 support-ten (2,2,1^8) kernels remain unsolved at the supplement stage. There is no S&lt;=14 theorem, no threshold below 250/429, no closure of n/2&lt;Delta&lt;250n/429 and no general equality theorem. The candidate 250/429 implication is not externally established.')]

S += [P('Confidence changes','H1x')]
conf=[['Item','Before audit','After audit'],['Raw bridge','Principal un-reconstructed risk','Internally supported; external review still open'],['S&lt;=13 finite closure','Claimed internal exact result','Retained after repairing corrupt evidence and helper audit'],['S&lt;=8 equality','Claimed internal exact result','Retained after clean regeneration and replay'],['r=12 / S&lt;=14','Incomplete','Still incomplete; no confidence promotion'],['Scheduler recovery','Configuration applied','Still unverified until observed launches']]
tt=Table([[P(x,'Smallx') for x in row] for row in conf],colWidths=[52*mm,55*mm,60*mm],repeatRows=1);tt.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#AAB7C4')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F5F8FA')]),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)]));S += [tt]

S += [PageBreak(),P('Session launch and utilisation audit','H1x'),P('Each trigger is an accounting identity. RAN means evidenced substantive scheduled research; it does not mean the historical 50-minute target was met. Missing time is never inferred from commits, prose or unit count. The 09:14 manual recovery is reported separately.')]
rows=[
('01:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('02:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('03:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('04:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('05:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('06:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('07:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('08:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('09:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('10:00','10:02:42','35m40s','11','SHORT'),('11:00','11:01:19','33m21s','20','SHORT'),('12:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('13:00','13:58:57','0m00s','0','MISSED/NO FORWARD'),('14:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('15:00','15:04:10','32m39s','9','LATE / TARGET N/A'),('16:00','16:03:51','28m36s','11','LATE / TARGET N/A'),('17:00','17:00:58','26m37s','13','SHORT'),('18:00','18:04:09','17m33s','16','LATE / TARGET N/A'),('19:00','19:58:31','0m00s','0','MISSED/NO FORWARD'),('20:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING'),('21:00','21:02:43','28m28s','11','SHORT'),('22:00','22:00:33','31m02s','9','SHORT'),('23:00','UNVERIFIED','UNVERIFIED','-','UNVERIFIED/MISSING')]
tab=[['Trigger','Earliest start','Verified forward','Units','Classification']]+[list(r) for r in rows]
tb=Table([[P(str(x),'Smallx') for x in r] for r in tab],colWidths=[22*mm,35*mm,34*mm,18*mm,58*mm],repeatRows=1)
tb.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#B8C2CC')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F6F8FA')]),('LEFTPADDING',(0,0),(-1,-1),3),('RIGHTPADDING',(0,0),(-1,-1),3),('TOPPADDING',(0,0),(-1,-1),2.5),('BOTTOMPADDING',(0,0),(-1,-1),2.5)]));S += [tb]

S += [Spacer(1,5),P('<b>Aggregate.</b> 23 scheduled triggers; 23 canonical records after reconciliation (9 existed before audit); 9 fully evidenced deliveries; 8 scheduled RAN; 0 met the historical 50-minute target; 5 short; 3 late-start/target-N/A; 2 zero-research deliveries; 13 missing/unverified. The eight evidenced research windows contain 408m39s of available time and 233m56s of closed forward intervals: 57.25% utilisation over those windows only. Manual recovery adds 11m10s and three units, giving a research lower bound of 245m06s when reported separately. Scheduled units: 100.'),P('<b>Separate activity.</b> One midnight audit, one manual-recovery research run and three administration/configuration episodes. None receives scheduled forward-session credit. No previous preservation segment is evidenced as displacing a later trigger; absent or late launch evidence is the dominant failure.'),P('<b>Prospective cutover.</b> The 40-minute standalone policy starts at 01:00:38 on 23 September. Its first three launches were not due during this audit. The next audit must check each for durable STARTED by trigger+5 minutes and first substantive checkpoint within ten minutes of entry. Configuration and last-run metadata are not recovery evidence.')]

S += [PageBreak(),P('Focused-session gate and next 24 hours','H1x'),P('<b>Gate count: 1/24.</b> Eight useful scheduled sessions ran, but none met the historical 50-minute qualification. Short useful work is not relabelled as no work. The formal go/no-go gate is not due. Its success condition is already provisionally met by the 250/429 threshold improvement, and the bounded-demand system is a credible finite-dimensional obstruction. Recommendation: continue, subject to the stop rules below.','Callout')]
priorities=[('1','Close the 42 r=12 kernels','Run the exact helper-aware supplement screen for support-ten (2,2,1^8). Stop with either a complete infeasibility certificate or an explicit survivor list.'),('2','Independent finite replay','Reimplement one load-bearing r=11 orbit/source stage, preferably support nine. Any count mismatch freezes S&lt;=13.'),('3','Graph-level stress','Seek actual positive-demand/high-load D2C fixtures and replay every bridge quantity. Bounded nonappearance proves no nonrealizability.'),('4','Return to the strip','Only after the finite and graph gates, combine the bridge with the high-codegree cluster or prove near-zero-demand stability preserving all balanced complete bipartite controls.'),('5','Measure launches, not settings','Enumerate every due trigger. Keep RAN, 40-minute compliance and focused-session credit separate; inspect the first three standalone launches individually.')]
for n,title,body in priorities:S += [KeepTogether([P(f'<b>{n}. {title}</b>','H2x'),P(body)])]
S += [P('Explicit stop/pivot criteria','H1x'),P('Freeze a finite conclusion on any independent orbit/source count mismatch. Freeze 250/429 on any raw bridge counterexample. Reject any equality lemma excluding odd balanced complete bipartite graphs. Do not turn an interrupted solve into evidence. At 24 genuinely credited focused sessions, make the continue/pivot decision from achieved mathematics rather than sunk cost.'),P('Deferred, not performed','H1x'),P('This audit did not independently reimplement every orbit canonicalizer or finish the r=12 supplement solve. It did not rerun the unchanged 250/429 scalar package because yesterday\'s exact replay remains current and no threshold change occurred. These limits are part of the evidentiary status, not omissions hidden by an “audit complete” label.')]

S += [P('Key files and commits','H1x')]
refs=[['Purpose','Identifier'],['Prior audit / threshold','9428d8359b85ab0330906beb3c1e583023ce0aba'],['Telemetry schema hardening','7499d32d03eee71d985ca6faf30bb590563bca1d'],['Raw bridge derivation','6d2bb26d604602cbd91c0a57dcaf369aace9b727'],['Actual-graph bridge regression','a5e1efe9657db4a251df60b97299bb4d25cc79fe'],['Zero-demand equality','fc05fdbf12a1adac2d57d063232f255300333342'],['r=11 closure','d10d7f7c8c507545fee996ab3c1e0a700314b07b'],['Audited predecessor','320ff91c4b3b1c64e98349788f9f971f65a9ef01'],['Audit note','project/research/general_n/2026-09-23-daily-red-team-audit-v1/DAILY_RED_TEAM_AUDIT.md']]
rt=Table([[P(x,'Smallx') for x in r] for r in refs],colWidths=[50*mm,117*mm],repeatRows=1);rt.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),navy),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#B8C2CC')),('VALIGN',(0,0),(-1,-1),'TOP'),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F6F8FA')]),('LEFTPADDING',(0,0),(-1,-1),4),('RIGHTPADDING',(0,0),(-1,-1),4),('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4)]));S += [rt]

doc.build(S,onFirstPage=header_footer,onLaterPages=header_footer)
print(OUT)
